Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-05, with the labels that each got.

#147 Typo fix: commited->committed
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 Add cinder flexvolume test example
  examples/cinder-flexvolume/nginx.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#134 Add cinder flexvolume test job
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Use default volume type in k8s cinder test
  examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#156 Switch to latest gophercloud
  Gopkg.lock
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Typo fix: fix some word error
  docs/cloud-providers.md
  docs/using-cinder-csi-plugin.md
  docs/using-cinder-standalone-provisioner.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Create OWNERS file in pkg/ingress
  pkg/ingress/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Add octavia-ingress-controller image build task in Makefile
  Makefile
  cluster/images/octavia-ingress-controller/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#157 Improve the config option for ingress controller
  pkg/ingress/config/config.go
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Add doc for octavia-ingress-controller
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#167 Support env variables for more arguments
  cmd/k8s-keystone-auth/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 Fix ldflags format for build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 Revert "Disable test-lb-octavia openlab job"
  .zuul.yaml
Labels: approved, cncf-cla: yes, size/XS

#153 Allow to read username and password from env variables
  cmd/client-keystone-auth/main.go
  docs/using-client-keystone-auth.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#172 Sync latest master to cpo may 14
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/volume/cinder/cinder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#154 add cloud-provider-openstack-format job
  .zuul.yaml
  cmd/client-keystone-auth/main.go
  hack/verify-gofmt.sh
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#171 Improve the doc of k8s-keystone-auth
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#176 Restore pre 1.10 openstack instance naming behavior
  pkg/cloudprovider/providers/openstack/metadata.go
  pkg/cloudprovider/providers/openstack/metadata_test.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#179 Cinder provisioner fixes
  pkg/volume/cinder/provisioner/clusterbroker.go
  pkg/volume/cinder/provisioner/iscsi.go
  pkg/volume/cinder/provisioner/iscsi_test.go
  pkg/volume/cinder/provisioner/mapper.go
  pkg/volume/cinder/provisioner/mapper_test.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/provisioner_test.go
  pkg/volume/cinder/provisioner/testutils_test.go
  pkg/volume/cinder/provisioner/vsbroker.go
  pkg/volume/cinder/volumeservice/actions.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#180 Install also make if not installed
  tools/install-distro-packages.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 Add SECURITY_CONTACTS for k/cpo
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#181 Update Kubernetes webhook auth documentaion
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#185 add possibility to specify connection limit in lbaas listener
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#183 Add cloning via PVC annotation
  pkg/volume/cinder/provisioner/clusterbroker.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/provisioner_test.go
  pkg/volume/cinder/provisioner/testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#182 Manila external provisioner
  Makefile
  cluster/images/manila-provisioner/Dockerfile
  cmd/manila-provisioner/main.go
  docs/using-manila-provisioner.md
  examples/manila-provisioner/README.md
  examples/manila-provisioner/cephfs/base-deploy.sh
  examples/manila-provisioner/cephfs/base-teardown.sh
  examples/manila-provisioner/cephfs/deployments.yaml
  examples/manila-provisioner/cephfs/rbac.yaml
  examples/manila-provisioner/cephfs/user-deploy/demo-deploy.sh
  examples/manila-provisioner/cephfs/user-deploy/demo-teardown.sh
  examples/manila-provisioner/cephfs/user-deploy/demo.yaml
  examples/manila-provisioner/cephfs/user-deploy/logs-manila.sh
  examples/manila-provisioner/cephfs/user-deploy/pvc.yaml
  examples/manila-provisioner/cephfs/user-deploy/sc.yaml
  examples/manila-provisioner/cephfs/user-deploy/vol-deploy.sh
  examples/manila-provisioner/cephfs/user-deploy/vol-teardown.sh
  examples/manila-provisioner/csi-cephfs/base-deploy.sh
  examples/manila-provisioner/csi-cephfs/base-teardown.sh
  examples/manila-provisioner/csi-cephfs/daemonsets.yaml
  examples/manila-provisioner/csi-cephfs/deployments.yaml
  examples/manila-provisioner/csi-cephfs/pods.yaml
  examples/manila-provisioner/csi-cephfs/rbac.yaml
  examples/manila-provisioner/csi-cephfs/services.yaml
  examples/manila-provisioner/csi-cephfs/statefulsets.yaml
  examples/manila-provisioner/csi-cephfs/user-deploy/demo-deploy.sh
  examples/manila-provisioner/csi-cephfs/user-deploy/demo-teardown.sh
  examples/manila-provisioner/csi-cephfs/user-deploy/demo.yaml
  examples/manila-provisioner/csi-cephfs/user-deploy/logs-cephfs.sh
  examples/manila-provisioner/csi-cephfs/user-deploy/logs-manila.sh
  examples/manila-provisioner/csi-cephfs/user-deploy/pvc.yaml
  examples/manila-provisioner/csi-cephfs/user-deploy/sc.yaml
  examples/manila-provisioner/csi-cephfs/user-deploy/vol-deploy.sh
  examples/manila-provisioner/csi-cephfs/user-deploy/vol-teardown.sh
  examples/manila-provisioner/filter-secrets.sh
  examples/manila-provisioner/generate-secrets.sh
  manifests/manila-provisioner/deployment.yaml
  manifests/manila-provisioner/rbac.yaml
  pkg/share/manila/client.go
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/sharebackend.go
  pkg/share/manila/sharebackends/args.go
  pkg/share/manila/sharebackends/cephfs.go
  pkg/share/manila/sharebackends/csicephfs.go
  pkg/share/manila/sharebackends/nfs.go
  pkg/share/manila/sharebackends/sharebackend.go
  pkg/share/manila/sharebackends/sharebackend_test.go
  pkg/share/manila/sharebackends/util.go
  pkg/share/manila/shareoptions/backend.go
  pkg/share/manila/shareoptions/common.go
  pkg/share/manila/shareoptions/openstack.go
  pkg/share/manila/shareoptions/parseoptions.go
  pkg/share/manila/shareoptions/protocol.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/share/manila/shareoptions/shareoptions_test.go
  pkg/share/manila/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#187 Add a conformance job for 1.11 release branch
  .zuul.yaml
Labels: cncf-cla: yes, lgtm, size/XS
