Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-06, with the labels that each got.

#194 Fix broken link in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#196 Trivial: Fix the path of policy.json
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 Add binary file name to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 Typo fix fromat->format/to to->to
  pkg/volume/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Write the command name of webhook
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#208 Fix the config sort of k8s-keystone-auth
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 Support to change the policy configmap for k8s-keystone-auth on the fly
  cmd/k8s-keystone-auth/main.go
  pkg/identity/keystone/authorizer.go
  pkg/identity/keystone/authorizer_test.go
  pkg/identity/keystone/config.go
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/token_getter.go
  pkg/identity/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#206 Add information about user's domain to the Extra data
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authenticator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#198 Allow synchronization between Keystone projects and K8s namespaces
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authenticator_test.go
  pkg/identity/keystone/config.go
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/sync.go
  pkg/identity/keystone/sync_test.go
  pkg/identity/keystone/syncconfig.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#205 Document cloning in the standalone-cinder provisioner
  docs/using-cinder-standalone-provisioner.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#209 make dep ensure verbose
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 Small README.md improvements
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#219 Sync role assignments
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authenticator_test.go
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/L
