Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-09, with the labels that each got.

#274 implement keep floatingip annotation
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#256 Refer getting started document in contributing.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#255 Install dep instead of glide in getting started doc
  docs/getting-started-provider-dev.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#263 Start using client.authentication.k8s.io/v1beta1 api for the client auth plugin
  cmd/client-keystone-auth/main.go
  docs/using-client-keystone-auth.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#259 Improve docs about auth data syncronization
  docs/using-auth-data-synchronization.md
  docs/using-client-keystone-auth.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#291 Avoid ERROR: logging before flag.Parse in UT
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/nodeserver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#294 Add/Update more CI jobs
  .zuul.yaml
Labels: cncf-cla: yes, size/XS

#296 Add doc to indicate the roles/bindings need to be created
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#290 Enhance comment about document
  pkg/cloudprovider/providers/openstack/metadata.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#283 Update to latest 1.12 release dependencies
  Gopkg.lock
  Gopkg.toml
  cmd/openstack-cloud-controller-manager/main.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/volume/cinder/attacher.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_util.go
  pkg/volume/cinder/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#300 Sync from Kubernetes master
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/volume/cinder/attacher_test.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_test.go
  pkg/volume/cinder/cinder_util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#304 Adds url to log new bug in contributing.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
