Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-12, with the labels that each got.

#383 Switch to Kubernetes 1.13.0 release
  Gopkg.lock
  Gopkg.toml
  cmd/cinder-csi-plugin/main.go
  cmd/cinder-flex-volume-driver/main.go
  cmd/cinder-provisioner/main.go
  cmd/client-keystone-auth/main.go
  cmd/k8s-keystone-auth/main.go
  cmd/manila-provisioner/main.go
  cmd/octavia-ingress-controller/main.go
  cmd/openstack-cloud-controller-manager/main.go
  pkg/cloudprovider/.import-restrictions
  pkg/cloudprovider/providers/openstack/metadata.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_metrics.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/mount/mount.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/flexvolume/cinder/drivers/rbd.go
  pkg/flexvolume/cinder_baremetal_util.go
  pkg/flexvolume/cinder_client.go
  pkg/flexvolume/flexvolume.go
  pkg/flexvolume/node/node.go
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authorizer.go
  pkg/identity/keystone/config.go
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/sync.go
  pkg/ingress/cmd/root.go
  pkg/ingress/controller/controller.go
  pkg/share/manila/provisioner.go
  pkg/util/mount/mount_linux.go
  pkg/util/mount/mount_windows.go
  pkg/volume/cinder/attacher.go
  pkg/volume/cinder/attacher_test.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_block.go
  pkg/volume/cinder/cinder_util.go
  pkg/volume/cinder/provisioner/clusterbroker.go
  pkg/volume/cinder/provisioner/iscsi.go
  pkg/volume/cinder/provisioner/mapper.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/rbd.go
  pkg/volume/cinder/provisioner/testutils_test.go
  pkg/volume/cinder/volumeservice/actions.go
  pkg/volume/cinder/volumeservice/connection.go
  staging/src/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#399 Move loadbalancer annotation to service in README file
  examples/loadbalancers/README.MD
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#398 Fix part of bug 372, try to use metadata to retrieve data first
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#384 manila-provisioner: added mounter option for csi-cephfs backend
  docs/using-manila-provisioner.md
  pkg/share/manila/sharebackends/csicephfs.go
  pkg/share/manila/sharebackends/sharebackend_test.go
  pkg/share/manila/shareoptions/backend.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#401 Do not run jobs for changes to documentation
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#405 Fix getting instance availability zone from Nova
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 Fix cloud controller manager role
  cluster/addons/rbac/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#409 Fix the ccm manifest file and RBAC definition
  cluster/addons/rbac/cloud-controller-manager-roles.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#410 Update doc: using-controller-manager-with-kubeadm
  docs/using-controller-manager-with-kubeadm.md
  manifests/controller-manager/kubeadm.conf
Labels: approved, cncf-cla: yes, lgtm, size/L

#385 Add doc for csi cinder usage
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#377 Implement Barbican as KMS provider for kubernetes
  Gopkg.lock
  Makefile
  cluster/images/barbican-kms-plugin/Dockerfile
  cmd/barbican-kms-plugin/main.go
  manifests/barbican-kms/encryption-config.yaml
  manifests/barbican-kms/pod.yaml
  pkg/kms/barbican/barbican.go
  pkg/kms/barbican/fake_barbican.go
  pkg/kms/client/client.go
  pkg/kms/encryption/aescbc/aescbc.go
  pkg/kms/encryption/aescbc/aescbc_test.go
  pkg/kms/server/server.go
  pkg/kms/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#393 Add Document to Install and Use Barbican KMS Plugin
  docs/using-barbican-kms-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#411 enhance ccm configuration file
  manifests/controller-manager/kubeadm.conf
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#344 [csi] add snapshot support
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: approved, cncf-cla: yes, lgtm, size/L
