Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-04, with the labels that each got.

#79 Keystone authorization improvement
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  examples/webhook/policy.json
  pkg/identity/keystone/authorizer.go
  pkg/identity/keystone/authorizer_test.go
  pkg/identity/keystone/authorizer_test_policy.json
  pkg/identity/keystone/policy.go
  pkg/identity/webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#82 Fix reliability of TestRoutes and TestVolumes
  Makefile
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/volume/cinder/attacher.go
  pkg/volume/cinder/attacher_test.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#84 Better environment vars support for standalone cinder service
  pkg/volume/cinder/volumeservice/connection.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#85 getConfig should work when config file is absent
  pkg/volume/cinder/volumeservice/connection.go
  pkg/volume/cinder/volumeservice/connection_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#77 Add more testing scenarios jobs against K8S+OpenStack
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#99 copy doc from main repo
  docs/cloud-providers.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#97 Fix the path to the cinder sample.
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#94 Add support for networking opts
  manifests/controller-manager/cloud-config
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#102 Add conformance e2e test pipeline
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 Check for existing names on csi CreateVolume
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#86 Migrate from Glide to dep for dependency management
  .travis.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  docs/using-controller-manager-with-kubeadm.md
  glide.lock
  glide.yaml
  tools/test-setup.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#106 Add ghugo as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Add pull policy for driver-registrar image to support local image built from latest source code
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#107 Add periodic jobs for E2E conformance tests
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#112 Squash unnecessary ERROR prefixes in logs
  cmd/openstack-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#113 Tolerate unknown sections / variables
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/flexvolume/cinder_client.go
  pkg/volume/cinder/volumeservice/connection.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Remove unnecessary MAINTAINERS.md file
  pkg/cloudprovider/providers/openstack/MAINTAINERS.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#117 bump csi manifests to v0.2.0
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#127 Switch to new OpenLab unit test job in release-1.9 branch
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Remove DEST variable redeclaration in the Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Small fixes in controller-manager manifests
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#142 Enforce running Makefile from $DEST
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#141 Add Snapshots to CSI Provider
  Gopkg.lock
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 Provide a hack a script to run make in a Container
  README.md
  hack/make.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#133 Add octavia-ingress-controller
  Makefile
  cmd/octavia-ingress-controller/main.go
  pkg/ingress/cmd/root.go
  pkg/ingress/config/config.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/client.go
  pkg/ingress/controller/openstack/neutron.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/ingress/controller/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
