Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-10, with the labels that each got.

#305 Set e2e to master until cpo 1.12 branch/tag is cut
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#293 fix nits in client-keystone-auth
  cmd/client-keystone-auth/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#303 Add detail info about controller public/unpublish
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#307 Fix up path to executable for cinder-csi-plugin
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#277 First pass at adding templates for keystone auth
  examples/webhook/keystone-apiserver-webhook.yaml
  examples/webhook/keystone-auth-certs-secret.yaml
  examples/webhook/keystone-deployment.yaml
  examples/webhook/keystone-policy-configmap.yaml
  examples/webhook/keystone-rbac.yaml
  examples/webhook/keystone-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#314 Update to Kubernetes 1.12.0 release
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#308 Batch update members in octavia-ingress-controller
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#282 Get a token using Keystone Application Credential
  cmd/client-keystone-auth/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#299 Fix typos issue in attacher.go
  pkg/volume/cinder/attacher.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#310 [Ingress] Support to specify backend service port name
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#313 Uniform command prompt
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#318 Automated cherry pick of #317: Export some methods in anticipation of a standalone cinder
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_metrics.go
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#317 Export some methods in anticipation of a standalone cinder provider
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_metrics.go
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#319 Add Manila Provisioner binary to Makefile clean
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 Typo fix: exisiting -> existing
  docs/using-manila-provisioner.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#326 New url for golint
  Makefile
Labels: cncf-cla: yes, size/XS

#322 [Ingress] Do not recreate octavia resources when the controller restarts
  pkg/ingress/cmd/root.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/ingress/controller/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#329 octavia-ingress-controller: Node sync improvement
  pkg/ingress/cmd/root.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#332 Update to k/k 1.13.0-alpha.1 version
  Gopkg.lock
  Gopkg.toml
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/volume/cinder/attacher_test.go
  pkg/volume/cinder/cinder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#333 [Ingress] Use TCP protocol for the lb
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#335 [Ingress] Add event support
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#331 Get NodeID from Metadata Service as fallback
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/openstack/openstack_metadata.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#321 Add volume list functions
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#330 Update Pull Request Template
  .github/ISSUE_TEMPLATE/cloud-provider-openstack-pr-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#338 Add adisky as reviewer to OWNERS file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
