Repository kubernetes/cloud-provider-openstack, pull requests merged in 2018-08, with the labels that each got.

#251 Run conformance periodic jobs on specific branches for master
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#252 Run conformance periodic jobs on specific branches for 1.10
  .zuul.yaml
Labels: cncf-cla: yes, size/S

#257 Add OS_DOMAIN_NAME on the manifest
  manifests/provisioner/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#261 Replace internal provisioner name with external one
  cluster/addons/storage-class/openstack/default.yaml
  docs/openstack-kubernetes-integration-options.md
  examples/persistent-volume-provisioning/cinder/cinder-storage-class.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 Add code-of-conduct.md
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#265 Cascading delete loadbalancer resources for Octavia
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#270 Adding snap building support to client-keystone-auth plugin.
  .gitignore
  snapcraft.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#272 Pulling docker for the build
  snapcraft.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#275 Make OpenStack cloud provider report a node hostname address
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#276 try to search floatingip first before creating it
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 implement InstanceShutdownByProviderID to openstack
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#246 Add Manila Provisioner binary to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#266 Update Cinder CSI driver to 0.3.0
  Gopkg.lock
  Gopkg.toml
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/L
