Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-01, with the labels that each got.

#414 Fix Octavia typo
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#415 Rename newNodes to readyWorkerNodes
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#416 Use worker node predicate directly
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#350 Add support for reading clouds.yaml
  Gopkg.lock
  docs/provider-configuration.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
  pkg/flexvolume/cinder_client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#419 [octavia-ingress-controller] Use HTTP for loadbalancing protocol
  docs/using-octavia-ingress-controller.md
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#418 Move kms packages to klog
  cmd/barbican-kms-plugin/main.go
  pkg/kms/barbican/barbican.go
  pkg/kms/encryption/aescbc/aescbc.go
  pkg/kms/server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#397 add a check when the volume detach failed,
  Gopkg.lock
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#367 client-keystone-auth supports client certificates
  cmd/client-keystone-auth/main.go
  pkg/identity/keystone/token_getter.go
  pkg/identity/keystone/token_getter_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#417 Sanitation on pkg/ingress/
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#427 Fix some typos in comment
  pkg/util/mount/mount_linux.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#425 Add support for selecting a specific cloud from clouds.yaml
  docs/provider-configuration.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#433 Add description for the floating ip created for external service
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#439 Add barbican-kms-plugin to gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#413 Remove dependency from csi-common
  Gopkg.lock
  Gopkg.toml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/server.go
  pkg/csi/cinder/utils.go
  pkg/csi/cinder/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#438 Improve the cfg options for octavia ingress controller
  pkg/ingress/config/config.go
  pkg/ingress/controller/openstack/client.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#442 octavia-ingress-controller: Add ingress information to openstack resources description
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#441 Fix t.Errorf() error message
  pkg/util/mount/mount.go
  pkg/volume/cinder/cinder_block_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#444 Add internal-network-name networking option
  docs/provider-configuration.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#447 octavia-ingress-controller: Doc improvement
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/L
