Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-10, with the labels that each got.

#783 Add OWNERS for manila CSI driver
  pkg/share/manila/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#773 Fix error when mounting /var/lib/kubelet/pods
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#786 Cinder CSI: Restore the original microversion, when the resize was made
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#792 Update share OWNERS file
  pkg/share/manila/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 Barbican KMS: use persistent client
  pkg/kms/barbican/barbican.go
  pkg/kms/barbican/fake_barbican.go
  pkg/kms/server/server.go
  pkg/kms/server/server_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#797 occm: Fix deleting internal service
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/network.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#801 Update octavia config
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#796 Add 1.16 conformance job
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#736 [csi-manila] added a basis for compatibility layers
  Gopkg.lock
  cmd/manila-csi-plugin/main.go
  examples/manila-csi-plugin/helm-deployment/templates/controllerplugin-statefulset.yaml
  pkg/csi/manila/capabilities/manilacapabilities.go
  pkg/csi/manila/capabilities/util.go
  pkg/csi/manila/compatibility/compatibility.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/manilaclient/client.go
  pkg/csi/manila/manilaclient/interface.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/options/compatibilityoptions.go
  pkg/csi/manila/sanity/fakemanilaclient.go
  pkg/csi/manila/sanity/sanity_test.go
  pkg/csi/manila/util.go
  pkg/csi/manila/util/manila.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#795 Update the dependencies to kubernetes-1.17.0-alpha.1
  Gopkg.lock
  Gopkg.toml
  cmd/openstack-cloud-controller-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#805 fix golint failures
  pkg/csi/cinder/mount/mount.go
  pkg/flexvolume/cinder_util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#814 fix golint failures
  pkg/autohealing/healthcheck/healthcheck.go
  pkg/autohealing/healthcheck/plugin_endpoint.go
  pkg/autohealing/healthcheck/plugin_nodecondition.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/server.go
  pkg/flexvolume/cinder/drivers/rbd.go
  pkg/flexvolume/metadata/metadata.go
  pkg/ingress/controller/controller.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/util/metadata/metadata.go
  pkg/util/mount/mount.go
  pkg/volume/volume.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
