Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-09, with the labels that each got.

#639 check not found before return error
  pkg/csi/cinder/controllerserver.go
Labels: cncf-cla: yes, lgtm, size/S

#747 magnum-auto-healer: Use Magnum resize API for the worker node repair
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#743 Do not Delete LB in Case of Security Group Reconciliation Errors
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#739 Add creating service by specifying a floating IP example
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#749 Update slack channel link
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#740 Update to k/k v1.16.0-beta.1
  .zuul.yaml
  Gopkg.lock
  Gopkg.toml
  cmd/openstack-cloud-controller-manager/main.go
  pkg/csi/cinder/mount/mount.go
  pkg/csi/cinder/mount/mount_mock.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/sanity/fakemount.go
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/shareoptions/openstackoptions.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/provisioner/iscsi.go
  pkg/volume/cinder/provisioner/iscsi_test.go
  pkg/volume/cinder/provisioner/mapper.go
  pkg/volume/cinder/provisioner/mapper_test.go
  pkg/volume/cinder/provisioner/mapperbroker.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/provisioner_test.go
  pkg/volume/cinder/provisioner/rbd.go
  pkg/volume/cinder/provisioner/rbd_test.go
  pkg/volume/cinder/provisioner/testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#753 Disable Octavia Job
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#748 Allow cinder volume live resize
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#723 Implement ValidateVolumeCapabilities
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#742 Fix loadbalancer legacy name detection
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#760 Change to networking/v1beta1 on dependent components and packages
  Gopkg.lock
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#745 Update Docker build to use Golang 1.12
  hack/make.sh
Labels: cncf-cla: yes, lgtm, ok-to-test, size/XS

#735 Deduplicate OpenStack auth functions
  cmd/client-keystone-auth/main.go
  docs/using-manila-csi-plugin.md
  docs/using-manila-provisioner.md
  pkg/autohealing/cloudprovider/register/register.go
  pkg/autohealing/config/config.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_test.go
  pkg/csi/manila/manilaclient/builder.go
  pkg/csi/manila/manilaclient/interface.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/options/openstackoptions.go
  pkg/csi/manila/sanity/fakemanilaclient.go
  pkg/flexvolume/cinder_client.go
  pkg/ingress/config/config.go
  pkg/ingress/controller/openstack/client.go
  pkg/kms/barbican/barbican.go
  pkg/share/manila/client.go
  pkg/share/manila/shareoptions/openstackoptions.go
  pkg/share/manila/shareoptions/shareoptions_test.go
  pkg/volume/cinder/volumeservice/connection.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#764 octavia-ingress-controller: [doc] Add Requirements and Caveats
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#756 Add info about v2 VPI not support in CSI
  docs/provider-configuration.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#769 Update k/k v1.16
  Gopkg.lock
  Gopkg.toml
  pkg/csi/cinder/mount/mount.go
  pkg/csi/cinder/mount/mount_mock.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/sanity/fakemount.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#767 Bump cinder CSI driver version to 1.1.0
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#768 Update compatibility matrix for cinder CSI
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#774 Add variable export in cloud controller doc
  docs/using-controller-manager-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#766 Update sidecar image versions
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#771 OCCM: Support 'loadBalancerSourceRanges' for Service
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
  pkg/util/util.go
Labels: cncf-cla: yes, lgtm, size/L

#775 Update docker image version
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  manifests/provisioner/deployment.yaml
  manifests/webhook/k8s-keystone-auth-pod.yaml
Labels: cncf-cla: yes, lgtm, size/S

#776 Fix closing of dirs in doSafeMakeDir
  pkg/util/mount/mount_linux.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 occm: Add doc for loadBalancerSourceRanges support
  docs/expose-applications-using-loadbalancer-type-service.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#785 Deprecate Standalone cinder
  .zuul.yaml
  README.md
  docs/using-cinder-standalone-provisioner.md
Labels: approved, cncf-cla: yes, lgtm, size/S
