Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-04, with the labels that each got.

#586 trivial: Fix link in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#579 Add snapshot example in CSI doc
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#578 Do not get load balancers in deleted or deleting status
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#589 Support listener timeouts as service annotations
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#574 Update to use beta in-tree CSINode object
  manifests/cinder-csi-plugin/csi-attacher-rbac.yaml
  manifests/cinder-csi-plugin/csi-provisioner-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#523 upgrade CSI to 1.1.0
  Gopkg.lock
  Gopkg.toml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#513 Add Support for Running CSI Sanity Tests
  Gopkg.lock
  Makefile
  cmd/cinder-csi-plugin/cloud-config
  cmd/cinder-csi-plugin/main.go
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/sanity/fakecloud.go
  pkg/csi/cinder/sanity/fakemetadata.go
  pkg/csi/cinder/sanity/fakemount.go
  pkg/csi/cinder/sanity/sanity_test.go
  pkg/csi/cinder/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#575 Adding support for CA specfication
  cmd/client-keystone-auth/main.go
  pkg/identity/keystone/token_getter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#596 Consolidate CSI Manifest
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-attacher-rbac.yaml
  manifests/cinder-csi-plugin/csi-provisioner-rbac.yaml
  manifests/cinder-csi-plugin/csi-snapshotter-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-snapshotter-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#587 k8s-keystone-auth authorization policy definition version 2
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authenticator_test.go
  pkg/identity/keystone/authorizer.go
  pkg/identity/keystone/authorizer_test.go
  pkg/identity/keystone/authorizer_test_policy_version2.json
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/policy.go
  pkg/identity/keystone/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
