Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-07, with the labels that each got.

#656 kubeadm documentation update
  docs/using-controller-manager-with-kubeadm.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#664 Update/refactor docs
  docs/getting-started-provider-dev.md
  docs/openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#624 Update sidecar to latest versions
  examples/cinder-csi-plugin/nginx.yaml
  examples/cinder-csi-plugin/snapshot/example.yaml
  examples/cinder-csi-plugin/topology/example.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#674 Use ``share`` rather than ``path`` for NFS
  pkg/csi/manila/shareadapters/nfs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#353 Remove unnucessary log and adjust some logic
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#670 Fix getVolume to return proper error
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 Update Ingress Resource API version
  Gopkg.lock
  docs/using-octavia-ingress-controller.md
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#657 Don't run jobs when .gitignore is updated
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#672 Add check for node to fix sanity errors
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_instances.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#655 trivial: Add manila-csi-plugin to .gitignore
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#676 Adds openstack instance to nodeserver
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#691 Add link to using-manila-csi-plugin.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#681 Update base image to debian
  cluster/images/cinder-csi-plugin/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#689 Return Precise Error Info NodePublishVolume
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#694 Improve magnum-auto-healer log
  pkg/autohealing/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#697 magnum-auto-healer: Ensure the server is powered off before updating the Heat stack
  pkg/autohealing/cloudprovider/openstack/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#682 Remove broken node before repairing
  pkg/autohealing/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#652 csi-manila: added initial support for snapshots
  Gopkg.lock
  docs/developers-csi-manila.md
  docs/using-manila-csi-plugin.md
  examples/manila-csi-plugin/README.md
  examples/manila-csi-plugin/nfs/dynamic-provisioning/pod.yaml
  examples/manila-csi-plugin/nfs/dynamic-provisioning/pvc.yaml
  examples/manila-csi-plugin/nfs/dynamic-provisioning/storageclass.yaml
  examples/manila-csi-plugin/nfs/secrets.yaml
  examples/manila-csi-plugin/nfs/snapshot/pod.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotclass.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotrestore.yaml
  examples/manila-csi-plugin/nfs/static-provisioning/pod.yaml
  examples/manila-csi-plugin/nfs/static-provisioning/preprovisioned-pvc.yaml
  examples/manila-csi-plugin/secrets.yaml
  manifests/manila-csi-plugin/csi-provisioner-manilaplugin.yaml
  manifests/manila-csi-plugin/csi-provisioner-rbac.yaml
  pkg/csi/manila/adapters.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/share.go
  pkg/csi/manila/shareadapters/nfs.go
  pkg/csi/manila/snapshot.go
  pkg/csi/manila/util.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#693 Fix getStorageSizeInGiga
  pkg/share/manila/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#701 magnum-auto-healer: Remove Node object after Heat stack update
  pkg/autohealing/cloudprovider/cloudprovider.go
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
  pkg/autohealing/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#426 Add application id into ccm
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#620 Add resize support for Cinder CSI
  Gopkg.lock
  examples/cinder-csi-plugin/resize/example.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/mount/mount.go
  pkg/csi/cinder/mount/mount_mock.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#704 csi-manila: roll-back storage resources on failure
  Gopkg.lock
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/manilaclient.go
  pkg/csi/manila/share.go
  pkg/csi/manila/snapshot.go
  pkg/csi/manila/util.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#707 Add manila-csi-plugin to make build
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#675 Fix sanity test (part)
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#698 Remove cinderv1 support from cloudprovider
  Gopkg.lock
  docs/provider-configuration.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#710 remove ExternalID function
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#688 Fix GetMaxVolLimit to return correct value
  docs/provider-configuration.md
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, size/M
