Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-03, with the labels that each got.

#507 octavia-ingress-controller document
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#510 Fix typo in documentation
  docs/using-octavia-ingress-controller.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#516 Trivial: Fix typo of CIDR
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#520 Change octavia ingress arguments from snake case to kebab case
  docs/using-octavia-ingress-controller.md
  pkg/ingress/config/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#480 Switch to Kubernetes v1.14.0-beta.1 and fix stale imports
  Gopkg.lock
  Gopkg.toml
  cmd/barbican-kms-plugin/main.go
  cmd/cinder-provisioner/main.go
  cmd/client-keystone-auth/main.go
  cmd/k8s-keystone-auth/main.go
  cmd/openstack-cloud-controller-manager/main.go
  pkg/cloudprovider/.import-restrictions
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/mount/mount.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/volume/cinder/attacher.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_block.go
  pkg/volume/cinder/cinder_test.go
  pkg/volume/cinder/cinder_util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#518 Support new annotation for Service
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#508 Add probe for CSI
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#532 Fix gophercloud digest in Gopkg.lock
  Gopkg.lock
Labels: approved, cncf-cla: yes, lgtm, size/XS

#526 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#512 Add 1.13 and 1.14 pipelines
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#528 Update kubernetes to v1.14.0-beta.2
  Gopkg.lock
  Gopkg.toml
  cmd/cinder-provisioner/main.go
  cmd/manila-provisioner/main.go
  cmd/openstack-cloud-controller-manager/main.go
  pkg/identity/keystone/sync.go
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/volume/cinder/provisioner/iscsi.go
  pkg/volume/cinder/provisioner/iscsi_test.go
  pkg/volume/cinder/provisioner/mapper.go
  pkg/volume/cinder/provisioner/mapperbroker.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/provisioner_test.go
  pkg/volume/cinder/provisioner/rbd.go
  pkg/volume/cinder/provisioner/rbd_test.go
  pkg/volume/cinder/provisioner/testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#538 Use Alpine for Cinder CSI
  cluster/images/cinder-csi-plugin/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#533 Allow to specify default value in cloud-config for openstack-internal…
  docs/provider-configuration.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#555 Update CI conformance jobs
  .zuul.yaml
Labels: cncf-cla: yes, size/S

#546 Give cloud-controller-manager permission to watch secrets
  cluster/addons/rbac/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#543 initialize explictly to enable verbose option
  cmd/cinder-csi-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#549 Improve load balancer name
  docs/expose-applications-using-loadbalancer-type-service.md
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#568 Update to k/k 1.14
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#567 Move periodic jobs back to OpenLab
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#564 Support to keep original client IP for the Service
  Gopkg.lock
  docs/expose-applications-using-loadbalancer-type-service.md
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#570 Update docs
  docs/getting-started-provider-dev.md
  docs/openstack-kubernetes-integration-options.md
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/S
