Repository kubernetes/cloud-provider-openstack, pull requests merged in 2019-02, with the labels that each got.

#471 Add lingxiankong to the OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#448 Update defaultMetadataVersion to latest
  pkg/cloudprovider/providers/openstack/metadata.go
  pkg/csi/cinder/openstack/openstack_metadata.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#434 Make usage of CCM cloud-config secret in CSI examples
  docs/using-cinder-csi-plugin.md
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-attacher-rbac.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-rbac.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-rbac.yaml
  manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#461 octavia-ingress-controller: Fix the floating ip description
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#466 Implement proxy protocol support for lbaas v2
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#475 Fix error output in client-keystone-auth
  cmd/client-keystone-auth/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#451 cinder-csi-plugin: Add cluster argument to the driver
  cmd/cinder-csi-plugin/main.go
  docs/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#430 Openstack cloud-config as Kubernetes secret
  docs/using-controller-manager-with-kubeadm.md
  manifests/controller-manager/cloud-config-secret.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#470 Update Cinder CSI Driver to CSI Spec 1.0.0
  Gopkg.lock
  Gopkg.toml
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/server.go
  pkg/csi/cinder/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#468 Update to use kubernetes-sigs/sig-storage-lib-external-provisioner
  Gopkg.lock
  Gopkg.toml
  cmd/cinder-provisioner/main.go
  cmd/manila-provisioner/main.go
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/volume/cinder/provisioner/iscsi.go
  pkg/volume/cinder/provisioner/iscsi_test.go
  pkg/volume/cinder/provisioner/mapper.go
  pkg/volume/cinder/provisioner/mapperbroker.go
  pkg/volume/cinder/provisioner/provisioner.go
  pkg/volume/cinder/provisioner/provisioner_test.go
  pkg/volume/cinder/provisioner/rbd.go
  pkg/volume/cinder/provisioner/rbd_test.go
  pkg/volume/cinder/provisioner/testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#457 Add support for topology aware dynamic volume provisioning
  docs/using-cinder-csi-plugin.md
  examples/cinder-csi-plugin/topology/example.yaml
  manifests/cinder-csi-plugin/csi-attacher-rbac.yaml
  manifests/cinder-csi-plugin/csi-provisioner-rbac.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack_metadata.go
  pkg/csi/cinder/openstack/openstack_mock.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#481 mv metadata to util
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/util/metadata/metadata.go
  pkg/util/metadata/metadata_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#478 Fix get SyncConfigMapName in config.go bug
  pkg/identity/keystone/config.go
  pkg/identity/keystone/keystone.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#443 New options validator for manila-provisioner
  docs/using-manila-provisioner.md
  manifests/manila-provisioner/rbac.yaml
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/sharebackends/args.go
  pkg/share/manila/sharebackends/cephfs.go
  pkg/share/manila/sharebackends/csicephfs.go
  pkg/share/manila/sharebackends/nfs.go
  pkg/share/manila/sharebackends/sharebackend_test.go
  pkg/share/manila/shareoptions/backend.go
  pkg/share/manila/shareoptions/common.go
  pkg/share/manila/shareoptions/openstackoptions.go
  pkg/share/manila/shareoptions/parseoptions.go
  pkg/share/manila/shareoptions/shareoptions.go
  pkg/share/manila/shareoptions/shareoptions_test.go
  pkg/share/manila/shareoptions/validator/dependsexpr.go
  pkg/share/manila/shareoptions/validator/identity.go
  pkg/share/manila/shareoptions/validator/matchexpr.go
  pkg/share/manila/shareoptions/validator/precludesexpr.go
  pkg/share/manila/shareoptions/validator/util.go
  pkg/share/manila/shareoptions/validator/validator.go
  pkg/share/manila/shareoptions/validator/validator_test.go
  pkg/share/manila/shareoptions/validator/valueexpr.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#482 support multiple subnets in lbaas
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#474 Add STAGE_UNSTAGE_VOLUME node capability
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/mount/mount.go
  pkg/csi/cinder/mount/mount_mock.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#492 manila: added osShareNetworkID option
  docs/using-manila-provisioner.md
  pkg/share/manila/share.go
  pkg/share/manila/shareoptions/shareoptions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#462 Fix Snapshot Feature, and Add volume restore from snapshot
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#491 Improve security group management for service provision
  Gopkg.lock
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#494 Add document section about csi version compatibility
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#289 Add debug output for cfg options
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#496 [octavia-ingress-controller] Support internal/external Ingress
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#493 merge isNotFound inside cloud provider
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/ingress/controller/openstack/client.go
  pkg/ingress/controller/openstack/neutron.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/util/errors/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#500 support ca-file parameter in CSI
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#477 Implement arguments fallback for client-keystone-auth
  cmd/client-keystone-auth/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#505 Make use of the same API versions for DaemonSet/Deployment/Statefulset
  manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
  manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/provisioner/deployment.yaml
  manifests/webhook/k8s-keystone-auth-ds.yaml
  manifests/webhook/k8s-keystone-auth-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#502 [octavia-ingress-controller] Support security group management
  pkg/ingress/config/config.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
  pkg/ingress/controller/utils.go
  pkg/ingress/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#506 [octavia-ingress-controller] Improve floating IP management
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
Labels: approved, cncf-cla: yes, lgtm, size/L
