Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-04, with the labels that each got.

#995 [manila-csi-plugin] improvements for docs regarding AZs / topology
  docs/using-manila-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#941 [cinder-csi-plugin] NodeGetVolumeStats() implementation
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/sanity/fakemount.go
  pkg/util/blockdevice/blockdevice_linux.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_mock.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1005 Improve the issue and PR template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1001 [cinder-csi-plugin] Run e2e and acceptance when update manifest in cinder CSI
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1006 [occm] Add e2e conformance job for release-v1.18
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1008 Bump Go version in make.sh helper script
  hack/make.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1013 [cinder-csi-plugin] Updated csi versions in cinder-csi-controllerplugin
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1017 Fix the build on non linux OS
  pkg/util/blockdevice/blockdevice_unsupported.go
  pkg/util/mount/mount.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/S

#1022 [cinder-csi-plugin] Add availability zone topology awareness for ephemeral storage
  examples/cinder-csi-plugin/inline/inline-example.yaml
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1014 [cinder-csi-plugin] nit: rename SnapshotReadyStatus to snapshotReadyStatus
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1026 Fix the release note guide
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1012 [cinder-csi-plugin] Add csi-migration-test go .zuul.yaml
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1025 [manila-csi-plugin] report fully qualified version
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1016 Update the doc of getting-started-provider-dev
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1023 [occm] Support multiple network names
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#996 [manila-csi-plugin] updates to k8s manifests and helm chart
  examples/manila-csi-plugin/helm-deployment/values.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1024 [cinder-csi-plugin] Fix 404 Docs and Enrich links
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1011 [cinder-csi-plugin] add Helm chart
  charts/cinder-csi-plugin/.helmignore
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/README.md
  charts/cinder-csi-plugin/templates/NOTES.txt
  charts/cinder-csi-plugin/templates/_helpers.tpl
  charts/cinder-csi-plugin/templates/cinder-csi-driver.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-rbac.yaml
  charts/cinder-csi-plugin/templates/storageclass.yaml
  charts/cinder-csi-plugin/values.yaml
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#1033 [k8s-keystone-auth] Disable the CI job for k8s-keystone-auth in release-1.17
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1036 [occm] Remove volume related code from occm
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_client.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
  pkg/cloudprovider/providers/openstack/openstack_volumes.go
  pkg/csi/cinder/controllerserver.go
  pkg/util/util.go
  pkg/volume/cinder/attacher.go
  pkg/volume/cinder/attacher_test.go
  pkg/volume/cinder/cinder.go
  pkg/volume/cinder/cinder_block.go
  pkg/volume/cinder/cinder_block_test.go
  pkg/volume/cinder/cinder_test.go
  pkg/volume/cinder/cinder_util.go
  pkg/volume/cinder/doc.go
  pkg/volume/cinder/volumeservice/actions.go
  pkg/volume/cinder/volumeservice/connection.go
  pkg/volume/cinder/volumeservice/connection_test.go
  pkg/volume/util/error.go
  pkg/volume/util/util.go
  pkg/volume/volume.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#1042 update reviewers list
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1038 [OCCM] Print error messages, when OpenStack client returns error
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#969 [cinder-csi-plugin] Add pagination support for ListVolumes
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
  pkg/util/errors/errors.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1043 Bump gophercloud dependencies
  go.mod
  go.sum
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/csi/manila/manilaclient/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1045 [cinder-csi-plugin] Support image-csi-plugin target in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1035 [cinder-csi-plugin] Add version into cinder CSI driver info
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/identityserver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#946 [cinder-csi-plugin] Fix csi cinder sanity testing failures
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/sanity/fakecloud.go
  pkg/csi/cinder/sanity/fakemount.go
  pkg/csi/cinder/sanity/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1049 [cinder-csi-plugin] Support image-csi-plugin target in Makefile - release-1.18
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1034 [cinder-csi-plugin] Allow force create snapshot
  docs/using-cinder-csi-plugin.md
  examples/cinder-csi-plugin/snapshot/example.yaml
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#976 [cinder-csi-pugin] Support reconcile volume attachements
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1040 [occm] make cascade deletion configurable
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#1029 [cinder-csi-plugin] Backport fixes to 1.17
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
