Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-10, with the labels that each got.

#1247 [cinder-csi-plugin] Update plugin docs [Part 1]
  README.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/migrate-to-ccm-with-csimigration.md
  docs/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1205 [manila-csi-plugin] Updated external-snapshotter to v2.1.1 and external-provisioner to v2.0.2
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/values.yaml
  docs/using-manila-csi-plugin.md
  examples/manila-csi-plugin/nfs/snapshot/snapshotclass.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml
  manifests/manila-csi-plugin/csi-controllerplugin-rbac.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1255 [manila-csi-plugin] Updated external-snapshotter to v2.1.1 and external-provisioner to v2.0.2 (release-1.19)
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/values.yaml
  docs/using-manila-csi-plugin.md
  examples/manila-csi-plugin/nfs/snapshot/snapshotclass.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml
  manifests/manila-csi-plugin/csi-controllerplugin-rbac.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1252 [occm] reuse deleteListeners in EnsureLoadBalancerDeleted
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1261 [cinder-csi-plugin] Do not ignore use-cloud config option
  pkg/csi/cinder/openstack/fixtures/clouds.yaml
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1259 Allow to specify container engine in the makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1264 [occm] update cloud-controller-manager flags
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1262 [all] Fix build-cross target in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1267 [cinder-csi-plugin] explicitly set cinder CSI sidecar timeouts to 3m
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1254 [cinder-csi-plugin] Improve docs [Part2]
  docs/cinder-csi-plugin/csc-tool.md
  docs/cinder-csi-plugin/examples.md
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#1266 [cinder-csi-plugin] handle a case when a volume was already resized
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1256 [octavia-ingress-controller] Support Ingress v1
  docs/using-octavia-ingress-controller.md
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1274 Fix format error
  .zuul.yaml
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1283 [occm] Documentation for occm metrics
  docs/metrics.md
  docs/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#1276 [Cinder-csi-plugin]Add toleration to CSI daemonset
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1249 [occm] Fix updating listeners
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1286 [occm] Fix updating listeners (release-1.19)
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1285 [manila-csi-plugin] Fix whitespaces and invalid dot
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1291 [manila-csi-plugin] Added appendShareMetadata volume parameter
  docs/using-manila-csi-plugin.md
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1296 [cinder-csi-plugin] update topology feature docs
  docs/cinder-csi-plugin/features.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1295 organize docs
  README.md
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/developers-guide.md
  docs/keystone-auth/using-auth-data-synchronization.md
  docs/keystone-auth/using-client-keystone-auth.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/manila-csi-plugin/developers-csi-manila.md
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1297 [DOC] Fix a doc deadlink
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
