Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-08, with the labels that each got.

#1138 [occm] Remove compare between LB opts as it's useless
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1130 [occm] make floating subnet optional
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1135 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1144 [occm] Split Octavia related functions
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#1148 [occm] changing connection-limit annotation not limited to Octavia
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#1153 [k8s-keystone-auth][doc] Fix keystone webhook documentation
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  examples/webhook/keystone-auth-certs-secret.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/webhook/k8s-keystone-auth-ds.yaml
  manifests/webhook/k8s-keystone-auth-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#1154 [cinder-csi-plugin] Update CSIDriver object version to v1
  charts/cinder-csi-plugin/templates/cinder-csi-driver.yaml
  manifests/cinder-csi-plugin/csi-cinder-driver.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1156 [manila-csi-plugin] Export location resolution moved into individual share adapters
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/shareadapters/cephfs.go
  pkg/csi/manila/shareadapters/nfs.go
  pkg/csi/manila/shareadapters/shareadapter.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1157 [manila-csi-plugin] Replaced ChooseExportLocation with FindExportLocation
  pkg/csi/manila/shareadapters/cephfs.go
  pkg/csi/manila/shareadapters/nfs.go
  pkg/csi/manila/util/exportlocation.go
  pkg/csi/manila/util/exportlocation_test.go
  pkg/csi/manila/util/manila.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1155 [occm] fix bug for network-id annotation
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1160 [occm] add octavia loadbalancer flavor option
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1163 fix nil pointer dereference in create loadbalancer func (#1055)
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: cncf-cla: yes, ok-to-test, release-note-none, size/XS

#1158 [octavia-ingress-controller] Use REGEX compare type for HOST_NAME l7 rule type
  docs/using-octavia-ingress-controller.md
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1150 [occm] update listener on Octavia annotation changes
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1165 [occm] Add version check for lb flavors support
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1171 [cinder-csi-plugin] Bump driver version to 1.2.1
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1174 [cinder-csi-plugin] Update helm chart to latest and bump other images
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
