Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-07, with the labels that each got.

#1111 [manila-csi-plugin] add OWNERS file
  pkg/csi/manila/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1107 [cinder-csi-plugin] update plugin to v1.18.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1113 Cleanup old references in owners and docs.
  OWNERS
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1114 [cinder-csi-plugin] Add test changes into zuul file
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1103 [occm] refactor keepClientIP and useProxyProtocol
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1120 [manila-csi-plugin] Fix volume in nodeplugin
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#1140 Fix `conversion from int to string yields a string of one rune` issues
  pkg/ingress/controller/openstack/neutron.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1115 [all][doc] Adjust doc by using doctoc tool
  docs/developers-csi-manila.md
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/getting-started-provider-dev.md
  docs/migrate-to-ccm-with-csimigration.md
  docs/using-auth-data-synchronization.md
  docs/using-barbican-kms-plugin.md
  docs/using-cinder-csi-plugin.md
  docs/using-client-keystone-auth.md
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  docs/using-magnum-auto-healer.md
  docs/using-manila-csi-plugin.md
  docs/using-octavia-ingress-controller.md
  docs/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
