Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-01, with the labels that each got.

#895 Remove chaosaffe from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, do-not-merge/invalid-commit-message, lgtm, release-note-none, size/XS

#877 Simplyfied dep management of k8s repos
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#891 update link of cloud-provider-openstack sig
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#898 Rewrite IngressClass comment
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#897 [cinder-csi-plugin] Returned non-err if volume not mounted
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#875 [manila-provisioner] Add get, create and update permissions for endpoints
  examples/manila-provisioner/cephfs/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#892 repair url in mysql-cinder-pd
  examples/mysql-cinder-pd/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#900 [manila-provisioner]: Added AvailabilityZone option to CreateOpts struct for manila share pv
  pkg/share/manila/share.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#838 [manila-provisioner] client code refactoring
  cmd/manila-csi-plugin/main.go
  cmd/manila-provisioner/main.go
  pkg/csi/manila/manilaclient/builder.go
  pkg/share/manila/client.go
  pkg/share/manila/client_test.go
  pkg/share/manila/manila_test.go
  pkg/share/manila/provisioner.go
  pkg/share/manila/share.go
  pkg/share/manila/sharebackends/args.go
  pkg/share/manila/sharebackends/nfs.go
  pkg/share/manila/sharebackends/sharebackend_test.go
  pkg/share/manila/sharebackends/util.go
  pkg/share/manila/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#884 CCM: set predictable and proper server IP addresses order
  go.mod
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#843 add Zuul CI job for csi-manila
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#873 modify webhook doc
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  examples/webhook/keystone-policy-configmap.yaml
  manifests/webhook/k8s-keystone-auth-ds.yaml
  manifests/webhook/k8s-keystone-auth-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#881 [csi-manila] return ABORTED on simultaneous CreateVolume/Snapshot
  docs/developers-csi-manila.md
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/responsebroker/responsebroker.go
  pkg/csi/manila/responsebroker/responsebroker_test_.go
  pkg/csi/manila/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#868 CinderCSI: Add cloning support
  examples/cinder-csi-plugin/clone/example-clone.yaml
  examples/cinder-csi-plugin/clone/sc.yaml
  examples/cinder-csi-plugin/clone/source-pvc.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#901 [cinder-csi-plugin] Add cloning docs
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#671 create tags and descriptions for snapshot
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#889 update links in pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
