Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-03, with the labels that each got.

#948 [cinder-csi-plugin] Fixing ca-file reference in README + adding link
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#942 [cinder-csi-plugin] Move pkg/csi/cinder/mount to pkg/util
  cmd/cinder-csi-plugin/main.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/utils.go
  pkg/util/metadata/metadata.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_mock.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#950 [openstack-cloud-controller-manager]: Fix version flag
  cmd/openstack-cloud-controller-manager/main.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#963 Remove myself from the maintainer list
  OWNERS
  pkg/cloudprovider/providers/openstack/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#958 Remove inactive repo owners
  OWNERS
  pkg/ingress/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#931 [cinder-csi-plugin] Enable resize e2e tests
  .zuul.yaml
  test/cinder-testdriver.go
  test/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#959 [cinder-csi-plugin] Add error handling for errors during az retrieval from MetaData service
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#953 [k8s-keystone-auth] Support role mapping
  docs/using-auth-data-synchronization.md
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  go.mod
  go.sum
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/authenticator_test.go
  pkg/identity/keystone/keystone.go
  pkg/identity/keystone/mock_IKeystone.go
  pkg/identity/keystone/sync.go
  pkg/identity/keystone/sync_test.go
  pkg/identity/keystone/sync_test.yaml
  pkg/identity/keystone/syncconfig.yaml
  pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#961 Improve the guideline of getting started
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#965 [docs] Fix formatting of Service annotations
  docs/expose-applications-using-loadbalancer-type-service.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#957 [k8s-keystone-auth] Add e2e test script
  .zuul.yaml
  tests/e2e/k8s-keystone-auth/test-authz.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#962 [OCCM] Improve documentation
  README.md
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/getting-started-provider-dev.md
  docs/openstack-cloud-controller-manager.md
  docs/openstack-kubernetes-integration-options.md
  docs/provider-configuration.md
  docs/using-auth-data-synchronization.md
  docs/using-controller-manager-with-kubeadm.md
  docs/using-keystone-webhook-authenticator-and-authorizer.md
  docs/using-magnum-auto-healer.md
  docs/using-octavia-ingress-controller.md
  docs/using-openstack-cloud-controller-manager.md
  manifests/controller-manager/cloud-config
  manifests/controller-manager/kubeadm.conf
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#972 Fix the file filtering in CI jobs
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#971 [k8s-keystone-auth] Fix e2e test script
  .zuul.yaml
  tests/e2e/k8s-keystone-auth/test-authz.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#861 [cinder-csi-plugin] scan block device size before resize
  docs/using-cinder-csi-plugin.md
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_test.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
  pkg/util/blockdevice/blockdevice_linux.go
  pkg/util/blockdevice/blockdevice_unsupported.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#977 [OCCM] Set default value for some options
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#975 Revert "[cinder-csi-plugin] Enable resize e2e tests"
  .zuul.yaml
  test/cinder-testdriver.go
  test/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#952 [cinder-csi-plugin] Improve Probe() call
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/sanity/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#979 Refine new PR description template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#949 [cinder-csi-plugin] Update side car container version
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#988 Update docs for make commands
  docs/getting-started-provider-dev.md
  docs/using-barbican-kms-plugin.md
  release-procedure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#986 [OCCM] Add annotation for creating health monitor
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#982 Parse and follow klog CLI flags
  cmd/client-keystone-auth/main.go
  cmd/octavia-ingress-controller/main.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/identity/keystone/token_getter.go
  pkg/ingress/cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#992 [OCCM] Fix CI
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#939 [manila-csi-plugin] added AZ/topology support
  cluster/images/manila-csi-plugin/Dockerfile.build
  cmd/manila-csi-plugin/main.go
  docs/using-manila-csi-plugin.md
  examples/manila-csi-plugin/README.md
  examples/manila-csi-plugin/helm-deployment/templates/controllerplugin-statefulset.yaml
  examples/manila-csi-plugin/helm-deployment/templates/nodeplugin-daemonset.yaml
  examples/manila-csi-plugin/helm-deployment/values.yaml
  examples/manila-csi-plugin/nfs/topology-aware/pod.yaml
  examples/manila-csi-plugin/nfs/topology-aware/pvc.yaml
  examples/manila-csi-plugin/nfs/topology-aware/storageclass.yaml
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/sanity/sanity_test.go
  pkg/csi/manila/util.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#999 [All] Update docker image tag to v1.18.0
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  manifests/webhook/k8s-keystone-auth-ds.yaml
  manifests/webhook/k8s-keystone-auth-pod.yaml
Labels: cncf-cla: yes, release-note-none, size/M

#998 [DOC] Extended the note for removing Manila Provider
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
