Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-12, with the labels that each got.

#1319 [cinder-csi-plugin][chart] Remove duplicate pull policy definition
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1330 Update docs
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/manila-csi-plugin/using-manila-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1334 [magnum-auto-healer] Fix autohealer restart issue
  pkg/autohealing/cloudprovider/openstack/provider.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1325 [octavia-ingress-controller] Add node name to pool member during creation
  pkg/ingress/controller/openstack/octavia.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1241 [cinder-csi-plugin]Add liveness probe
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1336 [magnum-auto-healer] Fix autohealer nil pointer bug
  pkg/autohealing/cloudprovider/openstack/provider.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1340 [magnum-auto-healer] Bump container image tag to v1.19.3
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1335 [cinder-csi-plugin] Bump driver version to 1.2.2
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1337 [cinder-csi-plugin] Switch CSI sidecar image repository to gcr
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1339 [manila-csi-plugin] Switch CSI sidecar image repository to gcr
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/values.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1342 Remove snapcraft.yaml from repo
  snapcraft.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1331 [cinder-csi-plugin][doc] update doc to link to internal doc instead of external links
  docs/cinder-csi-plugin/examples.md
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-client-keystone-auth.md
  docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1347 [occm] Fix the test case test_update_port
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1327 [occm] remove underbar of member name while updating loadbalancer
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1346 [occm] Refer to the correct error variable
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1344 [occm] Add handling for supported LBProvider
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#1348 [cinder-csi-plugin] Update external-snapshotter to v2.1.3
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1349 [manila-csi-plugin] Update external-snapshotter to v2.1.3
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/values.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1343 [cinder-csi-plugin] Example of Cinder CSI PVC Recovery
  docs/cinder-csi-plugin/examples.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1352 trivial: Correct casing of OpenStack
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-client-keystone-auth.md
  pkg/csi/cinder/identityserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1292 [k8s-keystone-auth] Fix authorization error
  pkg/identity/keystone/authorizer.go
  pkg/identity/keystone/authorizer_test.go
  pkg/identity/keystone/authorizer_test_policy_version2.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1341 Upgrade k/k dependency to v1.20
  cmd/openstack-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/.import-restrictions
  pkg/util/mount/mount.go
  pkg/util/mount/mount_mock.go
  tests/sanity/cinder/fakemount.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL
