Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-11, with the labels that each got.

#1309 [occm] Update openstack-cloud-controller-manager image tag in manifest
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1272 [cinder-csi-plugin] Add error handling for list fucntions before creating
  pkg/csi/cinder/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1310 [Doc] Add description for os-TLSInsecure
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1311 [occm]: add support for "tls-insecure", "trustee-id" and "trustee-password" options
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1312 Fix broken doc link
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1240 [cinder-csi-driver] bump container version
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1307 [cinder-csi-plugin] support ignore-volume-az
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1317 [docs] Fix broken link in Keystone docs
  docs/keystone-auth/using-client-keystone-auth.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
