Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-09, with the labels that each got.

#1182 [cinder-csi-plugin] Remove the pods-cloud-data volume
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  pkg/util/mount/mount.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1172 propose to add jichenjc as approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1170 [cinder-csi-plugin]update chart cacert location to /etc/caert
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1180 [cinder-csi-plugin] Update debian base image to v2.1.3
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#974 [cinder-csi-plugin] upgrade snapshot to v2.1.1
  docs/using-cinder-csi-plugin.md
  examples/cinder-csi-plugin/snapshot/example.yaml
  examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1067 [cinder-csi-plugin][manila-csi-plugin] Add Github workflow for releasing charts
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/README.md
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/README.md
  docs/using-manila-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#1185 [occm] Allow auth-url to partially depend on applicationCredentialSecret
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1073 [cinder-csi-plugin] support "multiattach" volume type
  docs/using-cinder-csi-plugin.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1123 Auth: add TLS client auth support
  docs/using-manila-csi-plugin.md
  docs/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1191 Remove index.yaml and add README.md
  README.md
  index.html
  index.yaml
Labels: cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1151 [all] Update k8s dependencies to v1.19.0
  cmd/openstack-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#1190 Bump up chart version to trigger chart release
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1198 [occm] Fix bug where pointer from local loop variable instead of array variable is used
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1209 [occm] Fix bug where pointer from local loop variable instead of array variable is used
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1199 Bump up chart version to trigger chart release (release-1.19)
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1212 [cinder-csi-plugin] Update snapshotter to 2.1.1 in release-1.19 branch
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1195 [All] Update docker image tag to v1.19.0
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1228 [occm] Check is timeout parameters for Octavia listener supported
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1229 [occm] Check octavia version for timeout params when creating listener
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note, size/M

#1227 [cinder-csi-plugin][manila-csi-plugin] Disable chart install job on Github actions workflow
  .github/workflows/pr.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1211 [cinder-csi-plugin] Update snapshotter to v2.1.1 in charts
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1226 [cinder-csi-plugin] [doc] update doc about VolumeAttributes is optional
  docs/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1231 [octavia-ingress-controller] Check if TLS field in Ingress spec is set
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1225 [occm][nit] remove unnecessary log
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1204 [cinder-csi-plugin] Add ephemeral disk type support
  docs/using-cinder-csi-plugin.md
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#1234 [octavia-ingress-controller] Check if TLS field in Ingress spec is set
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1218 [cinder-csi-plugin][manila-csi-plugin] Make cloud-config/cacert volume/volumeMounts configurable
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/secret.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1178 [occm] API requests & Loadbalancer reconciliation metrics
  go.mod
  pkg/cloudprovider/.import-restrictions
  pkg/cloudprovider/providers/openstack/metrics/metrics.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_metrics.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/util/openstack/keymanager.go
  pkg/util/openstack/loadbalancer.go
  pkg/util/openstack/network.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#1233 Only perform chart lint, remove install step (#1227)
  .github/workflows/config/ct.yaml
  .github/workflows/pr.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1210 [occm] Add log for NodeAddressesByProviderID
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1217 [cinder-csi-plugin] Add explict namespace definition into chart
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1213 [occm] lookup flavor name if only id is provided
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1216 [cinder-csi-plugin][manila-csi-plugin] Add chart releaser script
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1238 [occm] Added Octavia Availability Zones support for LoadBalancers
  docs/expose-applications-using-loadbalancer-type-service.md
  docs/using-openstack-cloud-controller-manager.md
  go.mod
  go.sum
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1243 [k8s-keystone-auth] Improve doc
  docs/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1219 [cinder-csi-plugin][manila-csi-plugin] Make cloud-config/cacert volume/volumeMounts configurable (release-1.19)
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/secret.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1235 [octavia-ingress-controller] Check if TLS field in Ingress spec is set
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1246 [occm] Adding some log (level 2)
  go.sum
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
