Repository kubernetes/cloud-provider-openstack, pull requests merged in 2020-06, with the labels that each got.

#1092 [octavia-ingress-controller] Fix typo in OIC code
  pkg/ingress/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1097 [doc]update doc to link to docker setup
  docs/getting-started-provider-dev.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1099 [occm] Add error message in RegisterCloudProvider()
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1105 Add serviceName to cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1096 [cinder-csi-plugin] Refactor Metadata
  cmd/cinder-csi-plugin/main.go
  go.mod
  go.sum
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_instances.go
  pkg/csi/cinder/openstack/openstack_metadata.go
  pkg/csi/cinder/utils.go
  pkg/util/metadata/metadata.go
  pkg/util/metadata/metadata_mock.go
  pkg/util/mount/mount.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1102 [occm] improve logic for floating IP creation
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#1110 [manila-csi-plugin] Move to charts dir
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/_helpers.tpl
  charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-clusterrolebinding.yaml
  charts/manila-csi-plugin/templates/controllerplugin-role.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rolebinding.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-service.yaml
  charts/manila-csi-plugin/templates/controllerplugin-serviceaccount.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/csidriver.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrolebinding.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-serviceaccount.yaml
  charts/manila-csi-plugin/values.yaml
  docs/using-manila-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1112 [occm] Add error handling for reading config
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
