Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-09, with the labels that each got.

#1649 [cinder-csi-plugin] make SA snapshot-controller-sa references match across templates
  charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1652 [OCCM][CI]: Remove openlab secret usage
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1654 [Charts] Do not check chart version in dev cycle
  .github/workflows/pr.yaml
  docs/developers-guide.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1648 [occm] Support re-use load balancer between Services
  Makefile
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  go.mod
  go.sum
  hack/verify-import-boss.sh
  pkg/ingress/controller/controller.go
  pkg/openstack/.import-restrictions
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/util/openstack/loadbalancer.go
  pkg/util/openstack/network.go
  pkg/util/util.go
  tests/e2e/cloudprovider/test-lb-service.sh
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
Labels: size/XXL, cncf-cla: yes, release-note-action-required, approved, lgtm

#1640 [cinder-csi-plugin] Add e2e test job
  .zuul.yaml
  tests/ci-csi-cinder-e2e.sh
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
  tests/playbooks/roles/install-csi-cinder/README.md
  tests/playbooks/roles/install-csi-cinder/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#1651 [CI] Make devstack local.conf configurable
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
  tests/playbooks/test-occm-e2e.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
