Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-06, with the labels that each got.

#1528 [manila-csi-plugin] Fix error connecting to nfs plugin when using cluster proxy
  go.mod
  go.sum
  pkg/csi/manila/csiclient/builder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1552 [magnum-auto-healer] Fix duplicated repair action (#1530)
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/config/config.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1556 [ magnum-auto-healer] Fix duplicated repair action (#1530)
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/config/config.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1555 [occm] Use CI job cloud-provider-openstack-test-occm
  .zuul.yaml
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1559 Cleanup examples dir
  examples/mysql-cinder-pd/README.md
  examples/mysql-cinder-pd/mysql-service.yaml
  examples/mysql-cinder-pd/mysql.yaml
  examples/persistent-volume-provisioning/cinder/cinder-full.yaml
  examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml
  examples/persistent-volume-provisioning/cinder/cinder-storage-class.yaml
  examples/persistent-volume-provisioning/cinder/example-pod.yaml
  examples/volumes/cinder/README.md
  examples/volumes/cinder/cinder-web.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#1561 [cinder-csi-plugin] add optional priorityClassName for CSI components
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1557 [magnum-auto-healer] Fix duplicated repair action (#1530)
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/config/config.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
Labels: cncf-cla: yes, lgtm, release-note, size/L

#1547 [doc] update keystone auth
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1558 [occm] Use CI job cloud-provider-openstack-test-occm
  .zuul.yaml
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1553 [k8s-keystone-auth]Add build for client-keystone-auth
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1551 [doc] [cinder-csi-plugin]update doc to make add cert clearer
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1431 [occm] Move CCM rbac to manifests/
  cluster/addons/storage-class/openstack/default.yaml
  manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
  manifests/controller-manager/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1550 [OCCM] Add new job for e2e conformance test
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1567 [occm] update url - moving CCM to manifests/
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1501 Update snapshots examples to start using v1 API
  examples/cinder-csi-plugin/snapshot/example.yaml
  examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotclass.yaml
  examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1569 fix the words to correct ones
  cmd/cinder-csi-plugin/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1568 [doc][cinder-csi-plugin]update doc to reflect snapshot version
  docs/cinder-csi-plugin/features.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1565 [cinder-csi-plugin] Deprecate nodeID flag
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  cmd/cinder-csi-plugin/main.go
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver_test.go
  tests/sanity/cinder/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1476 [cinder-csi-plugin] Allow multiple config files
  cmd/cinder-csi-plugin/main.go
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1496 [cinder-csi-plugin] Update csi-test from 3.1.0 to 4.2.0
  go.mod
  go.sum
  pkg/csi/cinder/nodeserver.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_mock.go
  tests/sanity/cinder/fakemount.go
  tests/sanity/cinder/sanity_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1573 [cinder-csi-plugin] update doc on deprecated params
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1513 [occm] Run e2e conformance test for v1.21
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1544 [cinder-csi-plugin] add cluster id to snapshot metadata
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#1532 [cinder-csi-plugin] Add controller get volume function support
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/driver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1576 Remove contrib dir
  contrib/gate_hook.sh
  contrib/post_test_hook.sh
  contrib/pre_test_hook.sh
  devstack/plugin.sh
  devstack/settings
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1577 [OCCM] Restore the previous name for e2e-conformance job
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1563 [cinder-csi-plugin] Resize filesystem of a larger volume created from a snapshot/volume
  go.mod
  go.sum
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1351 [occm] Add OVN to supported Octavia providers.
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1578 [cinder-csi-plugin] Bump snapshotter version to 4.0.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1572 [cinder-csi-plugin][doc] Update CSIMigration status
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
