Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-05, with the labels that each got.

#1511 [occm] Disable openstack-cloud-controller-manager CI job
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1495 [cinder-csi-plugin] Add log for POST and DELETE actions
  pkg/csi/cinder/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1517 [occm] Add role for serviceaccounts/token
  cluster/addons/rbac/cloud-controller-manager-roles.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1516 [manila-csi-plugin] helm: added clusterID value
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#1521 [occm] add missing RBAC for serviceaccount token
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1519 [manila-csi-plugin] Add cephfs-clientID to volume parameters
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/shareadapters/cephfs.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#1522 [cinder-csi-plugin] Cleanup: handle errors from GetDevicePath
  pkg/csi/cinder/nodeserver.go
  pkg/util/metadata/metadata.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1518 [Doc] Refactor dev guide
  CONTRIBUTING.md
  README.md
  docs/developers-guide.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1526 [all/helm] Pin appVersion to v1.21.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1533 [doc][occm]: update doc to fix a typo
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1537 [cinder-csi-plugin] helm: Expose scheduler constraints in values.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1530 [magnum-auto-healer] Fix duplicated repair action
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/config/config.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1504 [occm] recreate load balancer pool on protocol mismatch
  pkg/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1542 [occm] Enable cloud-provider-openstack-test-occm job
  .zuul.yaml
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M
