Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-11, with the labels that each got.

#1675 [manila-csi-plugin] ControllerExpandVolume: fix bad key for deleting from pendingVolumes (release-1.22)
  pkg/csi/manila/controllerserver.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#1682 [manila-csi-plugin] Remove cloud-provider-openstack-acceptance-test-csi-manila job trigger
  .zuul.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1672 Update devstack branch to stable/xena
  tests/playbooks/roles/install-devstack/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1691 [Helm Chart][CI] Fix ct lint parameter
  .github/workflows/pr.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1655 [cinder-csi-plugin] Enable volume expansion and volume cloning e2e tests
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1679 [Charts] Add logVerbosityLevel variable to all Helm charts
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#1690 [occm][CI] Use pre-built amphora image in DevStack
  tests/ci-occm-e2e.sh
  tests/e2e/cloudprovider/test-lb-service.sh
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1658 [occm] Fix listener, pool, healthmonitor's empty name
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#1689 [occm] make PROXY loadbalancer ingress suffix configurable
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#1685 [general] return error early to avoid nil pointer usage
  pkg/client/client.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1678 [occm] Make volume mounts configurable in Helm Chart
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#1692 [csi-plugins] Bump CSI sidecar containers versions
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1488 [cinder-csi-plugin] Add microversion to GetVolumeByName
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#1699 [octavia-ingress-controller] Include CA certs into Barbican secret
  pkg/ingress/controller/controller.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1705 [cinder-csi-plugin][charts] Remove snapshot controller yamls
  charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml
  charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
