Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-07, with the labels that each got.

#1579 [manila-csi-plugin] Add support for online volume expansion
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/values.yaml
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  examples/manila-csi-plugin/nfs/dynamic-provisioning/storageclass.yaml
  manifests/manila-csi-plugin/csi-controllerplugin-rbac.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
  pkg/csi/manila/manilaclient/client.go
  pkg/csi/manila/manilaclient/interface.go
  pkg/csi/manila/share.go
  pkg/csi/manila/util.go
  tests/sanity/manila/fake-secrets.yaml
  tests/sanity/manila/fakemanilaclient.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1570 [cinder-csi-plugin] Enable ephemeral e2e tests
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1583 [manila-csi-plugin] Use low verbosity logging by default
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1589 Fix `make import-boss` gate failure
  Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1590 [manila-csi-plugin] Do not populate nodeStageCache when an error occurred previously
  pkg/csi/manila/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1575 [cinder-csi-plugin]Avoid create tag from metadata req of snapshot
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/fake.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1582 [manila-csi-plugin] Consolidate log and error messages
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/share.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1580 [cinder-csi-plugin] Sync RBAC as per latest sidecar versions
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1594 [cinder-csi-plugin] Add example for generic ephemeral support
  docs/cinder-csi-plugin/examples.md
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  examples/cinder-csi-plugin/ephemeral/csi-ephemeral-volumes-example.yaml
  examples/cinder-csi-plugin/ephemeral/generic-ephemeral-volumes.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1605 [manila-csi-plugin] Add options for passing mount opts to cephfs-csi
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/shareadapters/cephfs.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1602 [cinder-csi-plugin] Remove redundant imagePullPolicy
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1609 [cinder-csi-plugin] Fix duplicate keys of tolerations
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
