Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-03, with the labels that each got.

#1418 [octavia-ingress-controller] Improve Ingress reconciliation
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#1427 [octavia-ingress-controller] Set log formatter
  pkg/ingress/cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1432 [cinder-csi-plugin] Enable Snapshot e2e tests
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1429 [cinder-csi-plugin] Ephemeral volumes: wait for volume status to be available
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1421 [cinder-csi-plugin] write dev guide for CSI version and spec version
  docs/cinder-csi-plugin/development.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1425 [octavia-ingress-controller] Improve Ingress reconciliation
  pkg/ingress/cmd/root.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/util/openstack/loadbalancer.go
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#1433 [cinder-csi-plugin] Ephemeral volumes: wait for volume to be available
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1426 [octavia-ingress-controller] Improve Ingress reconciliation
  pkg/ingress/cmd/root.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#1375 [occm] pattern based subnet detection for loadbalancers
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  go.mod
  go.sum
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_loadbalancer_subnet_match_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XL

#1434 [cinder-csi-plugin] Fix filesystem resize
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1422 [cinder-csi-plugin] Enable volume cloning e2e tests
  tests/e2e/csi/cinder/cinder-testdriver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1442 [occm] Fix creating fully populated loadbalancer
  .zuul.yaml
  pkg/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1390 [csi-plugin] Bump CSI spec to 1.3
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  go.mod
  go.sum
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/manila/controllerserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1443 [cinder-csi-plugin] Fix filesystem resize (#1434)
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1445 [cinder-csi-plugin] Refactor waitForVolumeStatus to be generic
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1450 [cinder-csi-plugin]update CSI logs Log.Infof to Log.Errorf in error case
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1430 [cinder-csi-plugin] Enabled Topology Support by default
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
  docs/cinder-csi-plugin/features.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1449 [OCCM] Set Hostname in load balancer status when using PROXY protocol
  .zuul.yaml
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1439 [cinder-csi-plugin] Check volume status after volume expand action
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
