Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-08, with the labels that each got.

#1611 [occm] add missing RBAC for serviceaccount token (#1521)
  .github/workflows/pr.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1612 Fix chart linter
  .github/workflows/pr.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1586 Refactor the openstack provider code
  pkg/openstack/instances.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/util/errors/errors.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, size/XL

#1615 [cinder-csi-plugin] Allow overridng kubelet dir in chart values
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#1592 [manila-csi-plugin] snapshot caps check
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  go.mod
  go.sum
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/share.go
  pkg/csi/manila/util.go
  pkg/csi/manila/volumesource.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm

#1620 [cinder-csi-plugin] Bump driver version for 1.22 release
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
Labels: size/XS, cncf-cla: yes, release-note-none, lgtm

#1619 [cinder-csi-plugin] Remove preStop hook
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: cncf-cla: yes, release-note-none, size/S, lgtm

#1601 [all] Update k/k dependency to v1.22.0
  Makefile
  go.mod
  go.sum
  tests/e2e/csi/cinder/cinder-testdriver.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, size/XL

#1622 [docs] Update the apiVersions for TokenReview, SubjectAcessReview
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1623 [docs] Update the apiVersions (#1622)
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1616 [manila-csi-plugin] pass CreateVolumeRequest.parameters as Volume.volume_context
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/validator/validator.go
  pkg/csi/manila/validator/validator_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1624 [manila-csi-plugin] Pass CreateVolumeRequest.parameters in volume context
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/validator/validator.go
  pkg/csi/manila/validator/validator_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1626 [All] Update CPO docker image tag to v1.22.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1629 Update mount-utils to 0.22.0
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none

#1631 Update mount-utils to 0.22.0
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none

#1614 cinder-csi: Disable uuid checks on XFS
  pkg/csi/cinder/nodeserver.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm
