Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-02, with the labels that each got.

#1400 [occm] add metrics documentation
  docs/metrics.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1399 [cinder-csi-plugin] Use values to configure livenessprobe in Helm chart
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1382 [cinder-csi-plugin] Fix pagination support for ListVolumes/ListSnapshots
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1395 [cinder-csi-plugin] Remove probe logging
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  pkg/csi/cinder/identityserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1364 [occm] validate flavor name, fallback on flavor id
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1402 [occm] validate flavor name, fallback on flavor id (release-1.20)
  pkg/cloudprovider/providers/openstack/openstack_instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1396 [occm] loadbalancer: add missing metric observations, improve logs
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/L

#1320 cinder-csi-plugin: upgrade resizer and attacher side car container
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#1404 Backport #1399 and #1395 to release 1.20
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  pkg/csi/cinder/identityserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1411 [cinder-csi-plugin] Removed CI Job cloud-provider-openstack-acceptance-test-csi-cinder
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1384 [core]: introduce a common openstack client package
  cmd/openstack-cloud-controller-manager/main.go
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/autohealing/cloudprovider/register/register.go
  pkg/autohealing/config/config.go
  pkg/client/client.go
  pkg/client/service.go
  pkg/cloudprovider/providers/openstack/openstack_client.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_test.go
  pkg/csi/manila/manilaclient/builder.go
  pkg/csi/manila/manilaclient/interface.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/options/openstackoptions.go
  pkg/identity/keystone/token_getter.go
  pkg/ingress/config/config.go
  pkg/ingress/controller/openstack/client.go
  pkg/kms/barbican/barbican.go
  pkg/openstack/.import-restrictions
  pkg/openstack/OWNERS
  pkg/openstack/doc.go
  pkg/openstack/instances.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
  pkg/openstack/routes.go
  pkg/openstack/routes_test.go
  pkg/util/metadata/metadata.go
  pkg/util/metadata/metadata_test.go
  pkg/util/util.go
  tests/sanity/cinder/fakecloud.go
  tests/sanity/manila/fakemanilaclient.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XXL

#1381 DOC: Add note about not contain blank in AZ
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1412 fix typo
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#1413 [occm] Fix loadbalancer.openstack.org/proxy-protocol docs
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
