Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-01, with the labels that each got.

#1353 [cinder-csi-plugin] chart: better optional cloud-config secret handling
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/templates/secret.yaml
  charts/cinder-csi-plugin/values.yaml
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/M

#1355 [All] Update container image tag to v1.20.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1358 [manila-csi-plugin] Updated CSIDriver object to v1
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/csidriver.yaml
  manifests/manila-csi-plugin/csidriver.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1357 [occm] don't error on unsupported octavia provider
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, priority/critical-urgent, release-note, size/XS

#1359 Update e2e-conformance jobs to latest releases
  .zuul.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1372 [csi-plugin] Bump charts version
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1363 [occm] don't error on unsupported octavia provider
  .github/workflows/pr.yaml
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#1374 trival: DOC: fix broken link and remove unused link
  docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1377 [all] Bump up chart-releaser-action version
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1378 [all] Bump up chart-releaser-action version
  .github/workflows/release.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1366 bump csi-provisioner to 2.1.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
  docs/cinder-csi-plugin/sidecarcompatibility.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1389 [all] Bump chart version to trigger release action
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1236 [all]refactory metrics code so that additional code can consume it
  pkg/cloudprovider/providers/openstack/metrics/metrics.go
  pkg/cloudprovider/providers/openstack/openstack.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
  pkg/cloudprovider/providers/openstack/openstack_routes.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_api.go
  pkg/metrics/metrics_reconcile.go
  pkg/util/openstack/keymanager.go
  pkg/util/openstack/loadbalancer.go
  pkg/util/openstack/network.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#1388 Add executable flag to openstack-cloud-controller-manager Dockerfile of user/group/other
  cluster/images/openstack-cloud-controller-manager/Dockerfile.build
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
