Repository kubernetes/cloud-provider-openstack, pull requests merged in 2021-04, with the labels that each got.

#1459 [manila-csi-plugin] Add --cluster-id option
  cmd/manila-csi-plugin/main.go
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/controllerserver_test.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/volumesource.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1452 [Helm manila-csi-plugin] Added priorityClassName to DaemonSet
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1447 [magnum-auto-healer] Fix k8s master node repair if it's volume-based
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1457 [cinder-csi-plugin] add snapshot controller to Helm Chart
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/_helpers.tpl
  charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml
  charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1461 [magnum-auto-healer] Fix k8s master node repair if it's volume-based
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1462 [magnum-auto-healer] Fix k8s master node repair if it's volume-based
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#1467 [magnum-auto-healer] Fix undefined param
  pkg/autohealing/cloudprovider/register/register.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1468 [magnum-auto-healer] Fix undefined param
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1477 fix the outdate link in using-openstack-cloud-controller-manager.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1471 [cinder-csi-plugin] Sanitize secrets in the requests
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/utils.go
  pkg/csi/cinder/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#1473 [manila-csi-plugin] close GRPC connections
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
  pkg/csi/manila/nodeserver.go
  tests/sanity/manila/fakecsiclient.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#1480 [manila-csi-plugin] close GRPC connections (release-1.20)
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
  pkg/csi/manila/nodeserver.go
  tests/sanity/manila/fakecsiclient.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#1489 [cinder-csi-plugin] disable cloning tests
  tests/e2e/csi/cinder/cinder-testdriver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1483 [cinder-csi-plugin] Fix typos on the word ephemeral
  pkg/csi/cinder/nodeserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#1484 nit: Remove unused global variables
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1458 [occm] OpenStack Cloud Controller Manager Helm Chart
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/README.md
  charts/openstack-cloud-controller-manager/templates/_helpers.tpl
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding-sm.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/templates/secret.yaml
  charts/openstack-cloud-controller-manager/templates/service-sm.yaml
  charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
  charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#1474 [OCCM] add support for TLS terminated loadbalancers
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/client/service.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1455 [cinder-csi-plugin] custom StorageClass in Helm Chart
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/custom_storageclass.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/S

#1440 [all] Update to k/k v1.21.0
  cmd/openstack-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/csi/cinder/nodeserver.go
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#1500 [cinder-csi-plugin] made ControllerUnpublishVolume call idempotent
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#1492 [cinder-csi-plugin] Tag volume with optional pvc/pv metadata
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/fake.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/M

#1503 [cinder-csi-plugin] Bump driver version
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1506 Bump helm charts minor version
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#1505 [All] Update docker image tag to v1.21.0
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
