Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-11, with the labels that each got.

#2023 [manila-csi-plugin] Add csi-provisioner's --extra-create-metadata as share metadata
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/values.yaml
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/controllerserver_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#1988 [occm] Protect from `AllocateLoadBalancerNodePorts=false`
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#1946 [occm] Support specifying a sort order for node addresses
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/instances.go
  pkg/openstack/instances_test.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test

#2030 Automated cherry pick of #1946: Support specifying a sort order for node addresses
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/instances.go
  pkg/openstack/instances_test.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2031 Automated cherry pick of #1946: Support specifying a sort order for node addresses
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/manila/validator/validator.go
  pkg/ingress/controller/controller.go
  pkg/kms/barbican/barbican.go
  pkg/openstack/instances.go
  pkg/openstack/instances_test.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
  pkg/util/errors/errors.go
  pkg/util/mount/mount.go
  tests/sanity/cinder/fakemount.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2037 [occm] Allow deleting LBs in ERROR status
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2040 [occm] LB: Stop recreating monitors if no-HTTP is forced
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2027 Fix gate: CI of cinder CSI failure
  go.mod
  go.sum
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm
