Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-03, with the labels that each got.

#1806 [cinder-csi-plugin]update doc on minor issues
  docs/cinder-csi-plugin/features.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1802 [occm] Allow service status changes in ClusterRole
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
  manifests/controller-manager/cloud-controller-manager-roles.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#1805 [cinder-csi-plugin]Add CapOnlineExpansion e2e test
  tests/e2e/csi/cinder/cinder-testdriver.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1797 [cinder-csi-plugin] bump CSI sidecar versions to latest
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1717 [openstack-cloud-controller-manager] Log warning when internal-lb=true and requesting external LB
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1809 [OCCM] Add --cluster-name=$(CLUSTER_NAME) support
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1711 [cinder-csi-plugin] Enable logs for e2e tests
  tests/ci-csi-cinder-e2e.sh
  tests/playbooks/roles/install-csi-cinder/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1817 Fix lint issue
  Makefile
  hack/verify-golint.sh
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1814 [cinder-csi-plugin] Add Doc for topology
  docs/cinder-csi-plugin/examples.md
  docs/cinder-csi-plugin/features.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm
