Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-09, with the labels that each got.

#1982 Revert "[ci] bump golang version to 1.19 in install-golang role"
  tests/playbooks/roles/install-golang/defaults/main.yml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1983 [CI] bump golang version to 1.19 in install-golang role
  tests/playbooks/roles/install-golang/defaults/main.yml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1978 [occm] Fix minor Inconsistency in `getMemberSubnetID`
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1943 Cherry pick test for ErrNotFound in IsNotFound checklist (#1942) to 1.24
  pkg/util/errors/errors.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1987 [manila-csi-plugin] Fix fake csi and manila clients for sanity-csi test
  tests/sanity/manila/fakecsiclient.go
  tests/sanity/manila/fakemanilaclient.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1975 Bump k8s deps to 1.25
  .gitignore
  cmd/tests/manila-csi-e2e-suite/manila_csi_e2e_suite_test.go
  go.mod
  go.sum
  pkg/csi/manila/csiclient/builder.go
  pkg/csi/manila/csiclient/client.go
  pkg/kms/client/client.go
  tests/e2e/csi/manila/manilavolume.go
  tests/e2e/csi/manila/testsuite.go
  tests/sanity/cinder/sanity_test.go
  tests/sanity/manila/fakecsiclient.go
  tests/sanity/manila/sanity_test.go
Labels: cncf-cla: yes, release-note-none, approved, lgtm, size/XL

#1986 [cinder-csi-plugin] Add option to ignore blockstorage microversion on older clouds
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#1944 cherry pick support mounting btrfs volumes by the cinder-csi-plugin (#1941) to 1.24
  cluster/images/cinder-csi-plugin/Dockerfile.build
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/manila/validator/validator.go
  pkg/ingress/controller/controller.go
  pkg/kms/barbican/barbican.go
  pkg/openstack/loadbalancer.go
  pkg/util/errors/errors.go
  pkg/util/mount/mount.go
  tests/sanity/cinder/fakemount.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1979 [occm] network-id and subnet-id in class settings
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#1989 update go version in GHA
  .github/workflows/release-cpo.yaml
Labels: size/XS, cncf-cla: yes, release-note-none

#1990 update image tags to v1.25.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1991 update chart versions to master
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1992 [occm] Skip External network with IPv6 for FIPs creation
  pkg/util/openstack/network.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2002 [manila-csi-plugin] Bump csi-snapshotter to v5
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/values.yaml
  manifests/manila-csi-plugin/csi-controllerplugin-rbac.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#1984 [occm] Manage Security Groups for Octavia
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test
