Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-12, with the labels that each got.

#2044 [all] update openstack version to zed
  tests/playbooks/roles/install-devstack/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2045 [all] upgdate gophercloud to 1.1.0
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2050 fix: remove leftover from bundled snapshot controller
  charts/cinder-csi-plugin/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2028 [cinder-csi-plugin] Add log v5 for CI
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1882 Remove neutron lbaas v1 version code
  README.md
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  manifests/controller-manager/cloud-config
  pkg/client/service.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
Labels: size/XXL, cncf-cla: yes, release-note-action-required, approved, lgtm

#2024 [cinder-csi-plugin] Update csi version
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2063 [OCCM] log about obtain instance ID failure
  pkg/openstack/instances.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm
