Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-04, with the labels that each got.

#1662 [cinder-csi-plugin]add snapshot test back into CI
  tests/e2e/csi/cinder/cinder-testdriver.go
  tests/e2e/csi/cinder/csi-volumes.go
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1820 update prometheus goclient to 1.11.1 to address CVE-2022-21698
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1813 [cinder-csi-plugin]add 'force-create' into tag param to support force
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1821 [occm] Fix the binary version
  Makefile
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1822 [occm] Get occm pod logs when CI job fails
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1811 [cinder-csi-pluging] Add pod logs for cinder e2e
  tests/ci-csi-cinder-e2e.sh
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1824 clean up inactive owners and reviewers
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1793 [OCCM] fix listener pop during iteration
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1823 [OCCM]refactory code to prepare instance V2 implementation
  pkg/openstack/instances.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1835 [cinder-csi-plugin][charts] typo secret.namespace
  charts/cinder-csi-plugin/templates/secret.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1826 fix: Address CVE-2022-27191
  go.mod
  go.sum
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test
