Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-07, with the labels that each got.

#1932 Automated cherry pick of #1793: fix listener pop during iteration
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note, kind/bug, approved, lgtm, ok-to-test

#1941 [cinder-csi-plugin] btrfs-volumes not mountable by cinder-csi-plugin
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#1942 occm: Fix not found checks for LoadBalancers do not cover all possible cases
  pkg/util/errors/errors.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#1940 [occm] Implement `container-store` configuration setting
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test
