Repository kubernetes/cloud-provider-openstack, pull requests merged in 2022-06, with the labels that each got.

#1904 [cinder-csi-plugin] Remove downstream from probe
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#1906 [cinder-csi-plugin] Remove downstream from probe (#1904)
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#1907 [ci] Pin k3s to v1.23.6+k3s1
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/roles/install-k3s/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1886 [cinder-csi-plugin] Refactor csi-cinder to improve code climate
  cmd/cinder-csi-plugin/main.go
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_test.go
  pkg/csi/cinder/server.go
  pkg/csi/cinder/utils.go
  tests/sanity/cinder/fakecloud.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#1810 [cinder-csi-plugin] nit: improve logs
  pkg/csi/cinder/controllerserver.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1913 occm: Fix LoadBalancer deletion when the underlying LoadBalancer does not exist
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note, kind/bug, approved, lgtm, ok-to-test

#1911 OpenSSL PEM generates PKCS #8 keys
  pkg/ingress/controller/controller.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#1915 OpenSSL PEM generates PKCS #8 keys (#1911)
  pkg/ingress/controller/controller.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1916 OpenSSL PEM generates PKCS #8 keys (#1911)
  pkg/ingress/controller/controller.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1887 [manila-csi-plugin] Refactor csi-manila to improve code climate
  cmd/manila-csi-plugin/main.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/csiclient/builder.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/share.go
  pkg/csi/manila/snapshot.go
  pkg/csi/manila/util.go
  pkg/csi/manila/validator/valueexpr.go
  pkg/csi/manila/volumesource.go
  tests/ci-csi-manila-e2e.sh
  tests/e2e/csi/manila/manilavolume.go
  tests/e2e/csi/manila/testsuite.go
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#1921 Backport to v1.24 [ci] Pin k3s to v1.23.6+k3s1 (#1907)
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/roles/install-k3s/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1917 occm: Fix LoadBalancer deletion when the underlying LoadBalancer does…
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1918 occm: Fix LoadBalancer deletion when the underlying LoadBalancer does…
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1926 make 1.24.0=>1.24.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#1927 update release procedure file
  release-procedure.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#1894 Improve manila csi driver chart adding fsGroupPolicy
  charts/manila-csi-plugin/templates/csidriver.yaml
  charts/manila-csi-plugin/values.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#1892 [ci] Enable default golangci-lint + revive
  .golangci-check.yaml
  Makefile
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#1928 [occm] Remove mostly broken default ca-certs mount from helm chart
  charts/openstack-cloud-controller-manager/values.yaml
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test
