Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-05, with the labels that each got.

#2223 [octavia-ingress-controller] Increase timeout for LB to get to ACTIVE state
  pkg/util/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2235 [OCCM] add environment variable for timeout
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2236 [OCCM] Doc: update statement about neutron lbaas removeal
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2227 Use ci-built occm in all e2e tests
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2237 [occm] fix daemonset annotations
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2240 Use dl.k8s.io instead of hardcoded GCS URIs
  tests/playbooks/roles/install-k3s/tasks/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2238 [cinder-csi-plugin] shrink image, remove unnecessary utils (#2233)
  Dockerfile
  tools/csi-deps-check.sh
  tools/csi-deps.sh
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#2252 Set git version variable during the build
  Makefile
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2248 [occm] LoadBalancers: Remove dead SG code
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2257 [occm]: fix blackhole route atomic delete logic
  pkg/openstack/routes.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2260 [occm]: fix blackhole route atomic delete logic (1.27 cherry-pick)
  pkg/openstack/routes.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2258 [occm]: fix blackhole route atomic delete logic (1.25 cherry-pick)
  pkg/openstack/routes.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2254 Fix CSI spec versions
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/values.yaml
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  pkg/csi/cinder/driver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2239 [occm] add secret enabled option
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/templates/secret.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2250 [occm] Replace call to Nova os-interfaces with direct Neutron call
  pkg/openstack/instances.go
  pkg/openstack/instancesv2.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2265 [all] Update to gophercloud 1.4.0
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm
