Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-03, with the labels that each got.

#2135 cinder csi: fix double snapshots package import
  pkg/csi/cinder/controllerserver.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2090 Optimize route reconciliation logic
  pkg/openstack/instances.go
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/util/errors/errors.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test

#2144 Cleanup OWNERS and change co-lead in project
  OWNERS
  README.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2132 simplify loadbalancer enable
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2141 Optimize route reconciliation logic cherry-pick to 1.26 (#2090)
  pkg/openstack/instances.go
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/util/errors/errors.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#2140 Optimize route reconciliation logic cherry-pick to 1.25 (#2090)
  pkg/openstack/instances.go
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/util/errors/errors.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#2139 [all] Use multi-stage docker builds and buildx for multi-arch
  .github/workflows/release-cpo.yaml
  Dockerfile
  Makefile
  cloudbuild.yaml
  cluster/images/barbican-kms-plugin/Dockerfile
  cluster/images/barbican-kms-plugin/Dockerfile.build
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
  cluster/images/k8s-keystone-auth/Dockerfile
  cluster/images/k8s-keystone-auth/Dockerfile.build
  cluster/images/magnum-auto-healer/Dockerfile
  cluster/images/magnum-auto-healer/Dockerfile.build
  cluster/images/manila-csi-plugin/Dockerfile
  cluster/images/manila-csi-plugin/Dockerfile.build
  cluster/images/octavia-ingress-controller/Dockerfile
  cluster/images/octavia-ingress-controller/Dockerfile.build
  cluster/images/openstack-cloud-controller-manager/Dockerfile
  cluster/images/openstack-cloud-controller-manager/Dockerfile.build
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
Labels: cncf-cla: yes, release-note, approved, lgtm, size/XL

#2145 [all] Fix cloudbuild
  Makefile
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2146 [all] Fix substitution of _SHORT_TAG in cloudbuild
  cloudbuild.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2126 [occm] Support members without subnet in fully populated LB
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2147 update dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, approved, lgtm, size/XL

#2149 use go 1.20
  Dockerfile
  cmd/openstack-cloud-controller-manager/main.go
  go.mod
  tests/playbooks/roles/install-golang/defaults/main.yml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2155 [all] Revert cloudbuild to gcr.io/k8s-testimages/gcb-docker-gcloud
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2150 occm: implement a support for atomic routes update cherry-pick to 1.25 (#2134)
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  go.mod
  go.sum
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/openstack/routes_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2152 occm: implement a support for atomic routes update cherry-pick to 1.26 (#2134)
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  go.mod
  go.sum
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/openstack/routes_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2156 update tags to v1.26.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2153 Update OWNERS
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2158 update tags to v1.25.5
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2162 Add dulek and mdbooth as reviewers
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2160 [cinder-csi-plugin] Helm: Add extraArgs support for containers
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2163 helm: cinder-csi: Add extraArgs support for containers
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2169 move to use registry.k8s.io
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2164 helm: cinder-csi: Add extraArgs support for containers (#2160)
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2171 modify images to use registry.k8s.io
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2176 chore: remove morremeyer as maintainer
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: size/XS, cncf-cla: yes, needs-ok-to-test, release-note, approved, lgtm

#2173 modify images to use registry.k8s.io
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2172 modify images to use registry.k8s.io
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2178 update helm github actions and versions release-1.26
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2180 update helm github actions and versions release-1.24
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2179 update helm github actions and versions release-1.25
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2177 update helm github actions and versions
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
  charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2184 fix lint of charts
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2186 update: update gophercloud
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm
