Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-02, with the labels that each got.

#2088 Replace deprecated command with environment file
  .github/workflows/release-cpo.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2100 fix test gate
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
  pkg/identity/keystone/token_getter.go
  tests/playbooks/roles/install-devstack/tasks/main.yml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2097 [occm] add annotation for real loadbalancer address
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2076 [octavia-ingress-controller] Add octavia.flavor-id option
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  pkg/ingress/config/config.go
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/octavia.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2068 [OCCM]nit: rename function WaitLoadbalancerActive
  pkg/openstack/loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2101 Automated cherry pick of #2100: fix testgate
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
  pkg/identity/keystone/token_getter.go
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2102 Automated cherry pick of #2100: fix testgate
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
  pkg/identity/keystone/token_getter.go
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2105 [cinder-csi-plugin] helm: Add imagePullSecret support
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2079 [occm] Allow user to specify common annotations
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding-sm.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/templates/secret.yaml
  charts/openstack-cloud-controller-manager/templates/service-sm.yaml
  charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
  charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2113 [occm] add annotation for real loadbalancer address cherry pick to 1.25
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2111 Update release process
  release-procedure.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2112 [occm] add annotation for real loadbalancer address cherry-pick to 1.26
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2108 Update k3s and test image to ubuntu 22
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2110 [occm] add load-balancer-address annotation doc
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2077 [cinder-csi-plugin] add support for cinder openstack api metrics
  cmd/cinder-csi-plugin/main.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_instances.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/metrics/metrics.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2071 cinder-csi doc: update trouble shooting with volume not extended
  docs/cinder-csi-plugin/troubleshooting.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2073 doc: cinder-csi-plugin - add general ephemeral disk usage
  docs/cinder-csi-plugin/examples.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2117 update tags to v1.24.6
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none

#2118 update tags to v1.25.4
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none

#2119 update tags to v1.26.1
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none

#2121 [occm] Reintroduce seeding of math/rand source
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2122 [release-1.26][occm] Reintroduce seeding of math/rand source
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2123 [release-1.25][occm] Reintroduce seeding of math/rand source
  Makefile
  cmd/openstack-cloud-controller-manager/main.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2103 Update registry k8s.gcr.io -> registry.k8s.io
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/values.yaml
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2125 Add cloudbuild.yaml for staging
  cloudbuild.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2127 [cinder-csi-plugin] use base image v1.4.3 for CSI cinder
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2130 use base image v1.4.3 for CSI cinder
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2131 use base image v1.4.3 for CSI cinder
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2133 Implement instance v2 interfaces
  pkg/openstack/instances.go
  pkg/openstack/instancesv2.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm
