Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-04, with the labels that each got.

#2170 drop support for docker hub
  .github/workflows/release-cpo.yaml
  Makefile
  release-procedure.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2188 [barbican-kms-plugin] Add manifest for barbikan-kms daemoset
  manifests/barbican-kms/ds.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2190 [occm] Don't allow internal Services to share an LB
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2194 update base images
  Dockerfile
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2198 [barbican-kms-plugin] Update Barbican KMS plugin documentation
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2195 [occm] Shared LBs - improve docs
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2168 [occm] Remove FIP on internal annotation addition
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2199 tests: Remove support for preinstalled images
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2196 Cinder CSI general update: update csi external container version
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2193 update dependencies
  go.mod
  go.sum
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/share.go
  pkg/csi/manila/snapshot.go
  pkg/csi/manila/volumesource.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/util/mount/mount.go
  pkg/util/openstack/loadbalancer.go
  tests/e2e/csi/manila/manilavolume.go
  tests/e2e/csi/manila/testdriver.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2203 update tags
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved

#2204 update tags
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none

#2208 [octavia-ingress-controller] Do not default Octavia provider to "octavia"
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  pkg/ingress/controller/openstack/octavia.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2211 ignore others than v1.* tags
  cloudbuild.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2214 remove version
  cloudbuild.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2215 remove version from cloudbuild
  cloudbuild.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2216 release 1.27.1
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2210 [occm] add priorityClassName to helm chart
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2221 [all] update image tags to v1.27.1
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2218 [util] Ignore proxies when calling Nova Metadata
  pkg/util/metadata/metadata.go
  pkg/util/metadata/metadata_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test
