Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-08, with the labels that each got.

#2306 [occm] Get IP addresses of neutron subports v3
  pkg/openstack/instances.go
  pkg/openstack/instancesv2.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#2320 [occm] Fix protocol case mismatch (tcp vs TCP)
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2318 [all] Add dulek and kayrus as approvers
  OWNERS
  README.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2314 [occm] Support for LB providers that do not implement the bulk update/create API call
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/ingress/config/config.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/util/openstack/loadbalancer_serial.go
  pkg/util/util.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test

#2324 ✨ Add --version flags to binaries
  cmd/barbican-kms-plugin/main.go
  cmd/cinder-csi-plugin/main.go
  cmd/client-keystone-auth/main.go
  cmd/k8s-keystone-auth/main.go
  cmd/manila-csi-plugin/main.go
  pkg/autohealing/cmd/root.go
  pkg/ingress/cmd/root.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2317 Add imagePullSecret support
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2279 [magnum-auto-healer] Fix Worker Nodes stuck in Ready,SchedulingDisabled status after repair by reboot
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/controller/controller.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2323 Manila: Add support for imagePullSecrets to helm chart
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2330 [release-1.26] [all] Add dulek and kayrus as approvers
  OWNERS
  README.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2334 update k8s deps to 1.28
  cmd/openstack-cloud-controller-manager/main.go
  go.mod
  go.sum
  pkg/autohealing/controller/controller.go
  pkg/kms/client/client.go
  pkg/kms/server/server.go
  pkg/kms/server/server_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2335 update docker base images. update newer golint
  Dockerfile
  Makefile
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2336 update tags to 1.28.0
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2337 update tags master
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2338 [cinder-csi-plugin] Fix multiarch builds of Cinder CSI
  tools/csi-deps.sh
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2340 [occm] Remove unused vars
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2332 [occm] Use standard service account name in OCCM helm chart
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/S, release-note-action-required, approved, lgtm, ok-to-test

#2345 [docs] :seedling: Update image repo in the release procedure
  release-procedure.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2344 Release 1.27.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  go.mod
  go.sum
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2347 [occm] Remove spurious space in OCCM values file
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test
