Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-07, with the labels that each got.

#2280 [occm] Wait for LB to be ACTIVE on HM update
  pkg/openstack/loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2288 Refactors and enhances the codebase of the cinder csi plugin
  cmd/cinder-csi-plugin/main.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2289 fixed Grammatical mistakes in barbican-kms-plugin
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2286 [helm] occm cinder-csi securityContext
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2290 Added comments and arranged the variable names
  cmd/manila-csi-plugin/main.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2292 Improved the grammar in sidecarcompatibility.md
  docs/cinder-csi-plugin/sidecarcompatibility.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2287 [occm] Delete unused SG rules with manage-security-groups
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2301 Corrected the grammar
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2297 [all]: Allocate array capacity in advance
  pkg/csi/cinder/driver.go
  pkg/csi/manila/driver.go
  pkg/identity/keystone/authenticator.go
  pkg/identity/keystone/keystone.go
  pkg/ingress/controller/openstack/octavia.go
  pkg/openstack/instances.go
  pkg/openstack/routes.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2296 [cinder-csi-plugin]: fix pagination, avoid unnecessary memory allocation, add more logs
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2302 [occm] Use `instanceIDFromProviderID()` function
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2299 [manila-csi-plugin]: Remove unused manila code
  cmd/manila-csi-plugin/main.go
  pkg/csi/manila/capabilities/manilacapabilities.go
  pkg/csi/manila/compatibility/compatibility.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/manilaclient/builder.go
  pkg/csi/manila/nodeserver.go
  pkg/csi/manila/options/compatibilityoptions.go
  pkg/csi/manila/share.go
  pkg/csi/manila/snapshot.go
  pkg/csi/manila/util.go
  pkg/csi/manila/volumesource.go
  tests/sanity/manila/sanity_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2293 [occm] Optimize `applyNodeSecurityGroupIDForLB()`
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2305 [occm] Delete sgs on reconfiguration
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2291 [occm] Make manage-security-groups work with OVN
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm
