Repository kubernetes/cloud-provider-openstack, pull requests merged in 2023-01, with the labels that each got.

#2064 Update dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, approved, lgtm, size/XL

#2067 [occm] Make sure LB status is updated immediately
  pkg/openstack/loadbalancer.go
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2074 [k8s-keystone-auth] Replace gorilla/mux with chi
  go.mod
  go.sum
  pkg/identity/keystone/keystone.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2072 [all] Add k8s.io/dynamic-resource-allocation to replaced deps
  go.mod
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2070 update tags to v1.26.0 release
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, lgtm

#2057 [cinder-csi-plugin] use newer base image for CSI cinder (#1994)
  cluster/images/cinder-csi-plugin/Dockerfile
  cluster/images/cinder-csi-plugin/Dockerfile.build
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2078 [release-1.25] Address CVE-2022-41717
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2080 [release-1.24] Address CVE-2022-41717
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2081 [release-1.23] Address CVE-2022-41717
  go.mod
  go.sum
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2082 [release-1.22] Address CVE-2022-41717
  go.mod
  go.sum
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/manila/validator/validator.go
  pkg/ingress/controller/controller.go
  pkg/kms/barbican/barbican.go
  pkg/openstack/loadbalancer.go
  pkg/util/errors/errors.go
  pkg/util/mount/mount.go
  tests/sanity/cinder/fakemount.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test
