Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-12, with the labels that each got.

#2736 Stop setting GOPROXY in Dockerfile
  Dockerfile
  tests/playbooks/roles/install-cpo-occm/README.md
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
  tests/playbooks/roles/install-csi-cinder/README.md
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/README.md
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
  tests/playbooks/roles/install-golang/tasks/main.yml
  tests/playbooks/roles/install-k3s-bare-single/tasks/main.yaml
  tests/playbooks/roles/install-k3s/tasks/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/playbooks/test-csi-manila-e2e.yaml
  tests/playbooks/test-occm-e2e.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2733 add f5 as supported LB
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/openstack.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2732 [occm]: remove InstancesV1 Zones method
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test

#2745 [manila-csi-plugin] Trivial fixups
  pkg/csi/manila/driver.go
  pkg/csi/manila/nodeserver.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2715 [docs] add missing parameters to StorageClass in multi-region-clouds.md
  docs/cinder-csi-plugin/multi-region-clouds.md
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2743 [cinder-csi-plugin] Add --with-topology opt
  cmd/cinder-csi-plugin/main.go
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  tests/sanity/cinder/sanity_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm

#2744 [cinder-csi-plugin] bump CSI sidecar versions to latest
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
  charts/cinder-csi-plugin/values.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm, ok-to-test

#2747 ci: host tuning in devstack
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2754 Update golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm
