Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-03, with the labels that each got.

#2559 Cut 1.28.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2535 [barbican-kms-plugin] Pass KeyId to EncryptResponse
  pkg/kms/server/server.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2563 [occm] Improve CCM docs in dual-stack context
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2561 [barbican-kms-plugin] Update KMS API to v2
  docs/barbican-kms-plugin/using-barbican-kms-plugin.md
  manifests/barbican-kms/encryption-config.yaml
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2557 [openstack-cloud-controller-manager] Remove enforcement of IPv6 LB as internal
  pkg/openstack/events.go
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2384 Convert outstanding commands to cobra
  cmd/cinder-csi-plugin/main.go
  cmd/client-keystone-auth/main.go
  cmd/k8s-keystone-auth/main.go
  cmd/openstack-cloud-controller-manager/main.go
  pkg/autohealing/cloudprovider/openstack/provider.go
  pkg/autohealing/cloudprovider/register/register.go
  pkg/autohealing/cmd/root.go
  pkg/autohealing/controller/controller.go
  pkg/autohealing/healthcheck/healthcheck.go
  pkg/autohealing/healthcheck/plugin_endpoint.go
  pkg/autohealing/healthcheck/plugin_nodecondition.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2565 [docs] Update the release procedure
  docs/release-procedure.md
  release-procedure.md
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm
