Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-05, with the labels that each got.

#2589 Bump versions for 1.30
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2594 [occm] add dnsPolicy feature
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2591 [manila-csi-plugin] Update manila dev doc regarding implemented features
  docs/manila-csi-plugin/developers-csi-manila.md
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2601 [occm] add a node selector support for loadbalancer services
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
  pkg/openstack/openstack.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm

#2607 [tests]: fix 1.28 release CI
  tests/playbooks/roles/install-devstack/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2608 [tests]: fix 1.29 tests CI
  tests/playbooks/roles/install-k3s/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2605 [release-1.28] [occm] add a node selector support for loadbalancer services
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
  pkg/openstack/openstack.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm
