Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-10, with the labels that each got.

#2640 [cinder-csi-plugin] ephemeral volume removal (#2602)
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  cmd/cinder-csi-plugin/main.go
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/noop_openstack.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/cinder/utils.go
  pkg/util/blockdevice/blockdevice_unsupported.go
  pkg/util/metadata/metadata.go
  tests/sanity/cinder/sanity_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test

#2688 [core] improved readability of lb funcs, switch to slices.Contains
  pkg/identity/keystone/sync.go
  pkg/openstack/instances.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/util/util.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2690 Update DEBIAN_IMAGE to bookworm
  Dockerfile
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2533 [charts] add support for podLabels and podAnnotations to occm and cinder-csi-plugin charts
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/_helpers.tpl
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/_helpers.tpl
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/values.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2692 [occm] remove instances v1 support
  go.mod
  pkg/openstack/instances.go
  pkg/openstack/instances_addresses.go
  pkg/openstack/instances_addresses_test.go
  pkg/openstack/instances_test.go
  pkg/openstack/instancesv2.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/openstack.go
  pkg/openstack/openstack_test.go
  pkg/openstack/routes_test.go
  pkg/util/util.go
Labels: size/XXL, cncf-cla: yes, release-note, approved, lgtm
