Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-02, with the labels that each got.

#2316 Add support to only run selected CSI services
  cmd/cinder-csi-plugin/main.go
  cmd/manila-csi-plugin/main.go
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/driver_test.go
  pkg/csi/cinder/identityserver_test.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/utils.go
  pkg/csi/manila/driver.go
  tests/sanity/cinder/sanity_test.go
  tests/sanity/manila/sanity_test.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm, ok-to-test

#2538 [release-1.28] [occm] Lookup ports by SG and not tags (#2355)
  go.mod
  go.sum
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2544 [ci] Bump golangci-lint for go 1.22
  Makefile
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2537 [release-1.28] [occm] Make sure we don't mask LB tests failures and fix what was failing
  pkg/openstack/loadbalancer.go
  tests/e2e/cloudprovider/test-lb-service.sh
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2480 cinder-csi: Adds support for managing backups (kubernetes#2473)
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/fake.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_backups.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: cncf-cla: yes, release-note, approved, lgtm, size/XL, ok-to-test

#2519 fix: add missing labels to resources
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/_helpers.tpl
  charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding-sm.yaml
  charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
  charts/openstack-cloud-controller-manager/templates/daemonset.yaml
  charts/openstack-cloud-controller-manager/templates/secret.yaml
  charts/openstack-cloud-controller-manager/templates/service-sm.yaml
  charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
  charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2166 [octavia-ingress-controller] Add annotations to keep floating IP and/or specify an existing floating IP
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  pkg/ingress/controller/controller.go
  pkg/ingress/controller/openstack/neutron.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm, ok-to-test
