Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-11, with the labels that each got.

#2697 [occm] passthrough context to gophercloud calls
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_sg.go
  pkg/openstack/loadbalancer_subnet_match.go
  pkg/openstack/loadbalancer_subnet_match_test.go
  pkg/openstack/openstack.go
  pkg/openstack/routes.go
  pkg/util/openstack/network.go
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2703 remove jichenjc from approvers
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2706 [occm]: exit on unreachable loadbalancer endpoint
  pkg/openstack/openstack.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2712 Fix CSI tests
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2705 [occm] fix ovn security groups
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/M, release-note-none, kind/bug, approved, lgtm

#2687 [csi-plugins] add support for PVC annotations
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/values.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/values.yaml
  cmd/cinder-csi-plugin/main.go
  cmd/manila-csi-plugin/main.go
  docs/cinder-csi-plugin/examples.md
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  docs/manila-csi-plugin/using-manila-csi-plugin.md
  go.mod
  go.sum
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/controllerserver_test.go
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/nodeserver.go
  pkg/csi/cinder/nodeserver_test.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  pkg/csi/csi.go
  pkg/csi/manila/controllerserver.go
  pkg/csi/manila/controllerserver_test.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/manilaclient/client.go
  pkg/csi/manila/manilaclient/interface.go
  pkg/csi/manila/options/shareoptions.go
  pkg/csi/manila/share.go
  pkg/csi/manila/volumesource.go
  pkg/util/util.go
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/sanity/cinder/fakecloud.go
  tests/sanity/manila/fakemanilaclient.go
Labels: cncf-cla: yes, release-note, approved, lgtm, size/XL

#2708 [magnum-auto-healer] use github.com/google/uuid package
  go.mod
  go.sum
  pkg/autohealing/cloudprovider/openstack/provider.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2716 [tests] bump devstack branch to stable/2023.2, fix python issues
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2701 Fix warnings reported while building container images
  Dockerfile
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2719 [occm] fix node internal/external IP order
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2720 [tests] bump openstack branch to stable/2024.2
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-devstack/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2721 [tests] bump ubuntu to 24.04 jammy
  docs/developers-guide.md
  tests/playbooks/roles/install-docker/defaults/main.yml
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm

#2684 [occm] Support Octavia load balancing method via annotation
  docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
  pkg/openstack/events.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_test.go
Labels: cncf-cla: yes, size/M, release-note, approved, lgtm, ok-to-test

#2730 Revert "[tests] bump openstack branch to stable/2024.2"
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-devstack/defaults/main.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2723 Automated cherry pick of #2722: prepare release 1.31.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/cinder-csi-plugin/multi-region-clouds.md
  docs/developers-guide.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  go.mod
  go.sum
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
  tests/playbooks/roles/install-docker/defaults/main.yml
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2724 prepare release 1.30.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/developers-guide.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  go.mod
  go.sum
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/tasks/main.yml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
  tests/playbooks/roles/install-docker/defaults/main.yml
  tests/playbooks/roles/install-k3s/defaults/main.yaml
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2722 prepare release 1.31.2
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/cinder-csi-plugin/multi-region-clouds.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  go.mod
  go.sum
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
  tests/playbooks/test-csi-cinder-e2e.yaml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
