Repository kubernetes/cloud-provider-openstack, pull requests merged in 2024-04, with the labels that each got.

#2566 [release-1.29] Remove enforcement of IPv6 LB as internal (#2557)
  pkg/openstack/events.go
  pkg/openstack/loadbalancer.go
Labels: cncf-cla: yes, release-note-none, size/S, approved, lgtm, ok-to-test

#2552 [occm] Allow changing cluster-name on existing deployments
  pkg/openstack/events.go
  pkg/openstack/loadbalancer.go
  pkg/openstack/loadbalancer_rename.go
  pkg/openstack/loadbalancer_rename_test.go
  pkg/openstack/loadbalancer_test.go
  pkg/util/openstack/loadbalancer.go
Labels: cncf-cla: yes, size/L, release-note, approved, lgtm

#2570 [occm] helm chart - added route section to cloud-config secret
  charts/openstack-cloud-controller-manager/Chart.yaml
  charts/openstack-cloud-controller-manager/templates/_helpers.tpl
  charts/openstack-cloud-controller-manager/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2569 [cinder-csi-plugin] define availability zone for snapshot backup
  docs/cinder-csi-plugin/using-cinder-csi-plugin.md
  pkg/csi/cinder/controllerserver.go
  pkg/csi/cinder/openstack/openstack.go
  pkg/csi/cinder/openstack/openstack_backups.go
  pkg/csi/cinder/openstack/openstack_mock.go
  pkg/csi/cinder/openstack/openstack_snapshots.go
  pkg/csi/cinder/openstack/openstack_volumes.go
  tests/sanity/cinder/fakecloud.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2583 [cinder-csi-plugin] [manila-csi-plugin] Update Cinder and Manila CSI charts maintainers
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm

#2581 Bump K8s to v1.30.0
  Dockerfile
  go.mod
  go.sum
  pkg/util/mount/mount_mock.go
  tests/playbooks/roles/install-golang/defaults/main.yml
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
