Repository kubernetes/cloud-provider-openstack, pull requests merged in 2025-07, with the labels that each got.

#2885 [cinder-csi-plugin] add POSIX shell to docker image
  tools/csi-deps-check.sh
  tools/csi-deps.sh
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm

#2902 [occm] Target control-plane nodes and tolerate CriticalAddonsOnly taint
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2906 update gophercloud v2.7.0
  go.mod
  go.sum
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2870 [occm] fix lbaas logs
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2872 [release-1.31] [cinder-csi-plugin] Don't report topology capability when --with-topology=False
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2938 [release-1.32] chore: bump dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2939 [release-1.31] chore: bump dependencies
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm

#2940 [release-1.33] prepare new 1.33.1 release
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/cinder-csi-plugin/multi-region-clouds.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2941 [release-1.32] prepare new 1.32.1 release
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/cinder-csi-plugin/multi-region-clouds.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2942 [release-1.31] prepare new 1.31.4 release
  charts/cinder-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/Chart.yaml
  charts/openstack-cloud-controller-manager/Chart.yaml
  docs/cinder-csi-plugin/multi-region-clouds.md
  docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
  docs/magnum-auto-healer/using-magnum-auto-healer.md
  docs/octavia-ingress-controller/using-octavia-ingress-controller.md
  examples/webhook/keystone-deployment.yaml
  manifests/barbican-kms/ds.yaml
  manifests/barbican-kms/pod.yaml
  manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
  manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
  manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
  manifests/magnum-auto-healer/magnum-auto-healer.yaml
  manifests/manila-csi-plugin/csi-controllerplugin.yaml
  manifests/manila-csi-plugin/csi-nodeplugin.yaml
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2947 [release-1.31] update alpine to latest patch release
  Dockerfile
  go.mod
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm, ok-to-test

#2949 Bump golang to 1.24.5
  Dockerfile
  go.mod
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2950 [release-1.32] Bump golang to 1.23.11
  Dockerfile
  go.mod
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2954 Remove mdbooth as a reviewer
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2742 tests: Bump DevStack to Epoxy (2025.1)
  tests/ci-csi-cinder-e2e.sh
  tests/ci-csi-manila-e2e.sh
  tests/ci-occm-e2e.sh
  tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
  tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
  tests/playbooks/roles/install-csi-manila/tasks/main.yaml
  tests/playbooks/roles/install-devstack/defaults/main.yaml
  tests/playbooks/roles/install-devstack/templates/local.conf.j2
  tests/playbooks/test-occm-e2e.yaml
  tests/scripts/create-gce-vm.sh
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
