Repository kubernetes/cloud-provider-openstack, pull requests merged in 2025-05, with the labels that each got.

#2887 Add stephenfin to approvers, reviewers
  OWNERS
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm

#2889 [manila-csi-plugin] helm: add release namespace in manila csi chart
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-role.yaml
  charts/manila-csi-plugin/templates/controllerplugin-rolebinding.yaml
  charts/manila-csi-plugin/templates/controllerplugin-service.yaml
  charts/manila-csi-plugin/templates/controllerplugin-serviceaccount.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-serviceaccount.yaml
  charts/manila-csi-plugin/templates/runtimeconfig-cm.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2759 [manila-csi-plugin] allow podSecurityContexts to be set in controllerplugin and nodeplugin
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2890 [manila-csi-plugin] helm: support additional volumes in manila csi chart
  charts/manila-csi-plugin/Chart.yaml
  charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
  charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/manila-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/S, release-note, approved, lgtm, ok-to-test

#2892 [cinder-csi-plugin]: helm-charts: use /etc/config/ for cloud.conf
  charts/cinder-csi-plugin/Chart.yaml
  charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
  charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
  charts/cinder-csi-plugin/values.yaml
Labels: cncf-cla: yes, size/S, needs-ok-to-test, release-note, approved, lgtm

#2894 [all] update deps to 1.33 k8s
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, release-note-none, approved, lgtm
