Repository kubernetes/cloud-provider-openstack, pull requests merged in 2025-04, with the labels that each got.

#2862 [cinder-csi-plugin] Don't report topology capability when --with-topology=False
  pkg/csi/cinder/driver.go
  pkg/csi/cinder/identityserver.go
  pkg/csi/manila/driver.go
  pkg/csi/manila/identityserver.go
Labels: cncf-cla: yes, size/M, release-note-none, approved, lgtm

#2878 [openstack-cloud-controller-manager (occm)] fix: wrap error to bubble it up
  pkg/openstack/loadbalancer.go
Labels: size/XS, cncf-cla: yes, release-note-none, approved, lgtm, ok-to-test

#2880 k8s-keystone-auth: properly handle token with no project scope
  pkg/identity/keystone/authenticator.go
Labels: size/XS, cncf-cla: yes, release-note, approved, lgtm
